README.md
cmd/mic/mic.go
deploy/infra/deployment.yaml
pkg/apis/aadpodidentity/v1/aadpodidentity_deepcopy_generated.go
pkg/apis/aadpodidentity/v1/types.go
pkg/cloudprovider/cloudprovider.go
pkg/crd/crd.go
pkg/k8s/client.go
pkg/k8s/fake.go
pkg/mic/mic.go
pkg/nmi/server/server.go

Add ability to apply bindings based on pod labels.
Enable Eventing for binding apply and removal.
Add simpler Sync loop
Handle binding and id create/delete/edit.
Other misc fixes.

Label match, events, binding/id create/del/edit, simplify sync loop

---

pkg/cloudprovider/cloudprovider.go
pkg/crd/crd.go
pkg/mic/mic.go
pkg/stats/stats.go
pkg/stats/stats_test.go

- Fix the issue where sp could get used as user assigned msi for underlying vm.
- Fetch the pod from cache.
- Reorg some code for better testability.
- Add stats

Fixes, add pod list from cache, stats

---

cmd/demo/main.go
deploy/demo/deployment.yaml
deploy/infra/deployment.yaml
pkg/nmi/server/server.go

Enable pod to pass resource endpoint for token

---

deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovidertest/cloudprovider_test_util.go
pkg/cloudprovider/vm.go
test/controller/azureidentitybinding-object.yaml
test/controller/simpletest-azureidentity-object.yaml
test/simple/simpletest-azureidentity-object.yaml
test/simple/simpletest-azureidentity-watch.sh

Move the test layering to vm client level from cloudprovider level, thus improving coverage.
Fix for #67

Move test layering and fix for #67

---

Makefile
images/mic/Dockerfile
images/nmi/Dockerfile

As indicated #94, it's overkill to use hyperkube.

Switch to alpine as base image

---

Jenkinsfile
Makefile
images/demo/Dockerfile

Also converted  the demo Dockerfile to an alpine-based image

Add Jenkinsfile for building and pushing images to registry

---

charts/aad-pod-identity/templates/infra.yaml
deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml

Add xtables.lock mount to support iptables -w

---

charts/aad-pod-identity/templates/infra.yaml
deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml

Update charts and deployment spec to match most recent versions
CC @kkmsft

update containers' images' versions

---

azure-pipeline.yml

Azure bot has not yet signed CLA. So adding the required changes as a user.

Add azure pipeline yaml file

---

pkg/k8s/client.go

@kkmsft I recreated the PR after rebasing.

Support aad-pod-identity in init containers

---

docs/design/concept.md
docs/tutorial/README.md
docs/tutorial/scripts/1-init-aks/3-create-aks.sh

- Update broken docs url
- Few typos and update to tutorial docs

Update docs and err msg in tutorial script

---

test/common/azure/azure.go
test/e2e/aadpodidentity_test.go
test/e2e/identityvalidator/identityvalidator.go

Add more debugging messages, move away from  using keyvault version, wait for assigned identity removal in the test.

---

test/e2e/setup.sh

@kkmsft I've set the retries to 10 times with wait interval of 6s. Read in another issue that the replication can take close to 2 mins in worst case scenario. This retry has mostly worked for me without any issues. We can increase the retries later if it still doesn't suffice.

Add retries to role assignment

---

docs/tutorial/README.md

Fixes a few typos in the tutorial doc.

fix typos in tutorial README

---

pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

resolves https://github.com/Azure/aad-pod-identity/issues/224

Determine resource mgr endpoint based on cloud name

---

README.md

Fix docs for namespaced behavior
https://github.com/Azure/aad-pod-identity/issues/245

Fix annotations fmt in docs

---

pkg/nmi/server/server.go

Retries have been added in NMI as part of my previous PR - https://github.com/Azure/aad-pod-identity/pull/272. Instead of returning a 404 after internal retries in all scenarios we need to determine the state and then respond with different status codes.
- If no assigned identity found in CREATED state for the request, then we will return `403` which is non-retriable status code in go-autorest adal lib. This means the pod is not part of the current sync cycle and will be processed as part of next sync cycle. By returning a 403 we ensure the retry isn't aggressive.
- If assigned identity found in CREATED state, but not found in ASSIGNED state, then we return a 404 which is a retriable status code. The CREATED state for the identity means, the pod is part of this sync …

Update error status code based on state

---

Dockerfile
Makefile
test/e2e/setup.sh

- Better build caching
- Custom args for e2e tests
- Detect failure on e2e/setup.sh

Random improvements

---

pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/nmi/server/server.go

- Enhance unit test for mic state flow check
- Log error
- Fix typo in function name in nmi

Enhance unit test for mic

---

deploy/infra/master/replicaset/deployment.yaml

Point the deployment yaml in master to 1.5-rc1

Point the deployment yaml in master to 1.5-rc1

---

deploy/infra/master/replicaset/deployment-rbac.yaml
deploy/infra/master/replicaset/deployment.yaml

bump version to 1.5-rc2

---

cmd/mic/main.go
cmd/nmi/main.go
pkg/logger/logger.go
pkg/mic/mic.go
pkg/mic/utils.go
pkg/nmi/server/server.go
pkg/nmi/server/utils.go
pkg/probes/probes.go

Abstract logging interface for use by multiple components - NMI and MIC

---

pkg/nmi/server/server.go
pkg/pod/pod.go
pkg/pod/pod_test.go
test/common/k8s/infra/infra.go
test/e2e/aadpodidentity_test.go
test/e2e/identityvalidator/identityvalidator.go
test/e2e/template/deployment.yaml

- Update whitelist e2e test to ensure mixed scenario works as expected
- Add unit tests
- Cleanup
- Add comments 
Addressing comments from previous PR

update e2e test + cleanup

---

README.md
deploy/infra/master/replicaset/deployment-rbac.yaml
docs/readmes/pod-identity-exception.md
examples/azurepodidentityexception.yaml

Add instruction for `AzurePodIdentityException`

Add docs for AzurePodIdentityException

---

CHANGELOG-1.5.md

Add changelog for v1.5

---

charts/aad-pod-identity/README.md

Add deprecation note for helm charts.

Add deprecation note for helm chart

---

CHANGELOG-1.5.md
deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml
deploy/infra/noazurejson/deployment-rbac.yaml
deploy/infra/noazurejson/deployment.yaml

bump to v1.5.1

---

test/common/k8s/pod/pod.go
test/e2e/aadpodidentity_test.go

Add a test which runs the identity validation test and the MIC failover parallely.

Validation and MIC failure e2e test

---

CHANGELOG-1.5.md
deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml
deploy/infra/noazurejson/deployment-rbac.yaml
deploy/infra/noazurejson/deployment.yaml

bump version to 1.5.2

---

pkg/nmi/server/server.go
pkg/nmi/server/server_test.go
pkg/nmi/server/utils.go
pkg/nmi/server/utils_test.go

Redact client id in NMI logs

---

test/e2e/README.md

Update the e2e README for system msi clusters

---

README.md
docs/readmes/README.features.md
docs/readmes/README.namespaced.md

This PR reorganizes the namespaced pods instructions to point to a README of its own.

Readme fixes for namespaced instructions

---

pkg/k8s/client_test.go

Fix data races in k8 client unit tests. 
Fixes https://github.com/Azure/aad-pod-identity/issues/355

Fix data races in k8s client unit tests

---

deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml
deploy/infra/noazurejson/deployment-rbac.yaml
deploy/infra/noazurejson/deployment.yaml
deploy/infra/rc/deployment-rbac.yaml
deploy/infra/rc/deployment.yaml
test/e2e/template/deployment-rbac.yaml

Add resource limits and requests.
Fixes #187 

Add resource limits and requests

---

pkg/crd/crd.go

fix nil log in struct

---

deploy/infra/rc/deployment-rbac.yaml
deploy/infra/rc/deployment.yaml

Change rc deployment to point to rc3

---

pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

Adds user agent to arm calls.
Fixes #386 

Add user agent to arm calls

---

deploy/infra/rc/deployment-rbac.yaml
deploy/infra/rc/deployment.yaml

Update the rc deploy file to 1.5.3-rc4

---

CHANGELOG-1.5.md

changelog for 1.5.3

---

CHANGELOG-1.5.md

Changelog text change to reflect the effect of the fix to list calls

---

pkg/mic/mic_test.go

fix possible data race in unit test

---

cmd/mic/main.go
cmd/nmi/main.go
go.mod
pkg/crd/crd.go
pkg/k8s/client.go
pkg/mic/mic.go
pkg/mic/mic_test.go
test/common/k8s/infra/infra.go
test/e2e/aadpodidentity_test.go
test/e2e/config/config.go
test/e2e/template/deployment-rbac.yaml

PR to merge to scale test branch.

Scale test 

---

pkg/crd/crd.go
pkg/mic/mic.go
pkg/mic/mic_test.go

- Use map for sync loop computation

Scale test

---

pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/mic/mic.go
pkg/stats/stats.go

- Add stats for PUT/GET calls
- Add stats for count of assigned ids created and deleted in each cycle

Add stats for PUT/GET and count

---

cmd/mic/main.go

- Update `createDeleteBatch` to 20
- Update `clientQps` to 5

update default values

---

pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

Check identity ids exists.
Fixes https://github.com/Azure/aad-pod-identity/issues/402

Check identity ids exists before return

---

docs/readmes/README.featureflags.md
docs/readmes/README.md

Add documentation for new flags in 1.5.3

---

pkg/nmi/server/server.go

Add application/json header for all return paths

---

cmd/nmi/main.go

Fixes https://github.com/Azure/aad-pod-identity/issues/434

fix glog flag parse error in nmi

---

Dockerfile

Update golang used to build binaries

---

azure-pipelines.yml

update go version in azure pipeline

---

docs/readmes/README.featureflags.md

Fix typos in feature flags documentation

---

charts/aad-pod-identity/templates/mic-deployment.yaml
cmd/mic/main.go
docs/readmes/README.featureflags.md
pkg/mic/mic.go
pkg/mic/mic_test.go
test/e2e/aadpodidentity_test.go
test/e2e/template/deployment-rbac-old.yaml
test/e2e/template/deployment-rbac.yaml

update immutable identity check + tests

---

test/e2e/aadpodidentity_test.go
test/e2e/config/config.go

remove unused tests and update rg case

---

Jenkinsfile

Update jenkinsfile to use branch for build

---

Jenkinsfile
pkg/nmi/iptables/iptables.go

changes for v1.5.5

---

pkg/nmi/iptables/iptables.go

Update rules len check for iptables

---

Jenkinsfile
pkg/nmi/iptables/iptables.go

Update rule check for iptables + Jenkinsfile

---

Jenkinsfile

add branch checkout for jenkins

---

charts/aad-pod-identity/Chart.yaml
charts/aad-pod-identity/crds/crd.yaml
charts/aad-pod-identity/templates/crds.yaml

This PR makes the Helm chart compatible with Helm 3 by keeping compatibility with Helm 2.
Fixes #444 
I'm not sure I've used to good way to handle the chart version, let me know.

#444 Support for Helm 3

---

Makefile
azure-pipelines.yml

Adds helm-lint to CI
Fixes https://github.com/Azure/aad-pod-identity/issues/460

add helm-lint to ci

---

cmd/mic/main.go
cmd/nmi/main.go

init klog before flag parse

---

Makefile

update image name in makefile

---

Jenkinsfile

update jenkins build to remove creds

---

cmd/mic/main.go

remove klog init for mic

---

azure-pipelines.yml

update azure pipeline trigger

---

cmd/mic/main.go
cmd/nmi/main.go

add logs for namespaced mode

---

Dockerfile
Makefile
azure-pipelines.yml
go.mod
test/e2e/template/busyboxds.yaml

Update project files to go1.14
Simplify azure-pipelines.yaml
Remove unnecessary go build args

Upgrade to go1.14

---

README.md
deploy/demo/aadpodidentity.yaml
deploy/demo/aadpodidentitybinding.yaml
deploy/demo/deployment.yaml

This PR allows developers to follow the demo in a copy-and-paste fashion to minimize any error when trying out pod identity. 
Fixes https://github.com/Azure/aad-pod-identity/issues/552.

chore: update README.md to improve demo experience

---

README.md
deploy/demo/aadpodidentity.yaml
deploy/demo/aadpodidentitybinding.yaml
docs/readmes/README.md
docs/readmes/README.namespaced.md
docs/readmes/README.troubleshooting.md
docs/readmes/README.validation.md
examples/rest-api/README.md
examples/rest-api/binding.yaml
examples/rest-api/identity.yaml

Add documentation regarding the breaking change introduced in v1.6.0 and a troubleshooting guide for aad-pod-identity.

chore: add docs for v1.6.0 breaking change and troubleshooting guide

---

pkg/nmi/managed.go
pkg/nmi/server/server.go
pkg/nmi/standard.go

Improves info and error logs for NMI

improve logs for NMI

---

README.md

- Add client-go issue url to the doc for reference

add client-go issue url to readme

---

.pipelines/e2e-tests-template.yml
.pipelines/unit-tests-template.yml
Makefile
azure-pipelines.yml
test/common/azure/azure.go
test/e2e/aadpodidentity_test.go
test/e2e/cluster_configs/vmas.json
test/e2e/cluster_configs/vmss.json
test/e2e/config/config.go

Adding e2e tests on ADO as a PR gate to reduce regressions introduced by PRs.
Fixes #568 

test: set up e2e test pipeline on ADO

---

README.md

This ensure we use expected subscription in multiple subs environment.

doc: add `--subscription` parameter to az cli commands

---

README.md
docs/readmes/README.role-assignment.md

Fixes https://github.com/Azure/aad-pod-identity/issues/618.
cc @bq1756

docs: reduce ambiguity in demo and role assignment docs

---

README.md

add support information to readme

---

docs/readmes/README.app-exception.md
examples/azurepodidentityexception.yaml

docs: update docs for pod-identity exception

---

pkg/nmi/server/server.go

Fixes https://github.com/Azure/aad-pod-identity/issues/584.

chore: change status code returned from NMI for errors

---

deploy/demo/aadpodidentity-sp-cert.yaml
deploy/demo/aadpodidentity-sp.yaml

Updates to the correct case for SP examples
fixes #646 

update typed namespacedname case for sp example

---

docs/readmes/README.monitoring.md

Describe the components prometheus metrics endpoints

doc: list components prometheus enpoints

---

pkg/nmi/iptables/iptables.go

Checking if the length of the iptable rules in the `aad-metadata` chain equals 3 is not sufficient as it's possible the rules were changed underneath. To ensure the rules are what we expect it to be, check if existing rules match all expected rules. If any difference in the rules, then flush and recreate the chain.

fix: check iptable rules match expected

---

pkg/crd/crd.go

- Adds default known types to scheme to prevent errors while reestablishing watch due to network timeouts

add default known types to scheme

---

pkg/pod/pod.go
test/e2e/framework/identityvalidator/identityvalidator_helpers.go
test/e2e/multiple_identities_test.go

feat: trigger MIC sync when a pod label changes

---

.pipelines/e2e-tests-template.yml

Fixes https://dev.azure.com/azure/aad-pod-identity/_build/results?buildId=12444&view=logs&jobId=7f33e5bd-7764-5d8a-ba2e-506e078b9c3f.

ci: do not overwrite REGISTRY environment variable if it is defined

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

docs: add requirements to PR template and test standard to CONTRIBUTING.md

---

.gitignore
.pipelines/unit-tests-template.yml
Makefile
README.md
codecov.yml

ci: add code coverage as part of CI

---

.github/PULL_REQUEST_TEMPLATE.md

docs: fix broken test standard link in GitHub Pull Request template

---

docs/readmes/README.featureflags.md
test/e2e/backward_compat_test.go
test/e2e/block_instance_metadata_test.go
test/e2e/disruptive_test.go
test/e2e/framework/helm/helm_helpers.go
test/e2e/framework/iptables/iptables_helpers.go
test/e2e/gatekeeper_test.go
test/e2e/identity_exception_test.go
test/e2e/init_containers_test.go
test/e2e/invalid_identities_test.go
test/e2e/liveness_probe_test.go
test/e2e/multiple_identities_test.go
test/e2e/node_test.go
test/e2e/single_identity_test.go

- add e2e test for block-instance-metadata
- removed `[PR]` tag from test cases since we no longer skip any test case.
fixes #422

test: add e2e test for block-instance-metadata

---

.pipelines/deploy-aks-cluster.yml
.pipelines/deploy-aks-engine-cluster.yml
.pipelines/e2e-tests-template.yml
.pipelines/nightly.yml
.pipelines/pr.yml
.pipelines/soak-tests-template.yml
test/e2e/Makefile
test/e2e/README.md
test/e2e/backward_compat_test.go
test/e2e/block_instance_metadata_test.go
test/e2e/framework/config.go
test/e2e/framework/helm/helm_helpers.go

- fixes https://github.com/Azure/aad-pod-identity/issues/694
- deflake https://dev.azure.com/azure/aad-pod-identity/_build/results?buildId=12702&view=results

test: add aks as part of pr and nightly test

---

manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
manifest_staging/deploy/infra/deployment-rbac.yaml
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/managed-mode-deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment-rbac.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml
test/e2e/framework/iptables/iptables_helpers.go

chore: remove privileged: true for NMI daemonset

---

test/e2e/backward_compat_test.go
test/e2e/block_instance_metadata_test.go
test/e2e/e2e_suite_test.go
test/e2e/framework/convenience.go
test/e2e/framework/helm/helm_helpers.go
test/e2e/framework/iptables/iptables_helpers.go
test/e2e/framework/mic/mic_helpers.go
test/e2e/liveness_probe_test.go
test/e2e/node_test.go

install aad-pod-identity in kube-system namespace during the test suite so that it works in an AKS cluster with limited egress traffic.

ci: install aad-pod-identity in kube-system namespace

---

.pipelines/e2e-tests-template.yml
.pipelines/load-tests-template.yml
.pipelines/soak-tests-template.yml
.pipelines/unit-tests-template.yml
Dockerfile
go.mod

Update to go1.15

---

docs/design/concept.md

Fixed typo for azureIdentityBinding

Fixed typo

---

docs/design/concept.md

Guiding Principals --> Guiding Principles

Fixed Grammar

---

.pipelines/e2e-tests-template.yml
.pipelines/soak-tests-template.yml
test/e2e/e2e_suite_test.go
test/e2e/framework/config.go

ci: do not install / uninstall pod identity deployment in soak test

---

.github/PULL_REQUEST_TEMPLATE.md

fixes https://github.com/Azure/aad-pod-identity/issues/766

chore: update pr github template

---

cmd/nmi/main.go

fix: initialize klog flags for NMI

---

.pipelines/load-tests-template.yml
.pipelines/soak-tests-template.yml
test/e2e/framework/helm/helm_helpers.go

ci: fix e2e failure in nightly test pipeline

---

.github/ISSUE_TEMPLATE/bug_report.md
README.md
docs/readmes/README.role-assignment.md
docs/readmes/README.troubleshooting.md
hack/role-assignment.sh

docs: automate role assignments and improve troubleshooting guide

---

docs/readmes/README.known-issues.md

fixes #725 
Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? **no**

docs: add doc for deleting/recreating identity with same name

---

.pipelines/soak-tests-template.yml

fix soak test failure in https://dev.azure.com/azure/aad-pod-identity/_build/results?buildId=14040&view=results.

ci: fix image not found error in soak tests

---

README.md
docs/readmes/README.best-practices.md
docs/readmes/README.md

docs: add best practices documentation

---

README.md

docs: update pod cidr to non-host traffic for NMI

---

.pipelines/e2e-tests-template.yml
.pipelines/load-tests-template.yml
.pipelines/soak-tests-template.yml
.pipelines/unit-tests-template.yml
test/e2e/cleanup.go
test/e2e/framework/azure/vm_manager.go
test/e2e/framework/azure/vmss_manager.go
test/e2e/framework/timeout.go
test/e2e/node_test.go

test: s/1.15.0/1.15 & exclude existing identities when updating

---

_config.yml

Revert a36d91497a393d9ea2bc6ff088839d65e21a31db

Revert "Set theme jekyll-theme-cayman"

---

manifest_staging/charts/aad-pod-identity/templates/crds.yaml

fixes #823
**Please answer the following questions with yes/no**: no

fix: remove extra indentation in crd.yaml

---

test/e2e/framework/iptables/iptables_helpers.go
test/e2e/liveness_probe_test.go

test: health check with podIP from the busybox container

---

pkg/cloudprovider/truncate.go
pkg/cloudprovider/truncate_test.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

fixes #813
**Please answer the following questions with yes/no**: no
Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? No

fix: account for 150+ identity assignment and unassignment

---

.pipelines/scan-images.yml

Removing `--ignore-unfixed` for trivy image scan. We can use the result and open Github issues for the CVE to track and resolve. 

chore: update image scan to log vulnerabilities

---

.pipelines/deploy-aks-cluster.yml
.pipelines/deploy-aks-engine-cluster.yml
.pipelines/load-tests-template.yml
hack/role-assignment.sh
manifest_staging/charts/aad-pod-identity/README.md
manifest_staging/charts/aad-pod-identity/values.yaml
test/e2e/README.md
test/e2e/framework/azure/vm_manager.go
test/e2e/framework/azure/vmss_manager.go
test/e2e/framework/config.go
website/content/en/docs/Demo/standard_walkthrough.md
website/content/en/docs/Getting started/role-assignment.md

fixes #837 
**Please answer the following questions with yes/no**: no

fix: s/cluster resource group/node resource group

---

website/content/en/docs/Configure/custom_cloud.md

- Add docs for configuring `aad-pod-identity` in custom cloud
fixes #845 

docs: add docs for configuring in custom cloud

---

website/content/en/_index.html

docs: fix broken links and typo

---

website/content/en/docs/Demo/standard_walkthrough.md
website/content/en/docs/Getting started/role-assignment.md

docs: use `az aks show` for node resource group & more convenient command to run role assignment script

---

website/content/en/docs/Troubleshooting/_index.md

docs: update troubleshooting doc for network policies

---

manifest_staging/charts/aad-pod-identity/README.md
manifest_staging/charts/aad-pod-identity/templates/identities.yaml
manifest_staging/charts/aad-pod-identity/values.yaml
website/content/en/docs/Concepts/azureidentity.md

feat: use map for azureIdentities instead of list in helm chart

---

Dockerfile

ref #908
- [] included documentation

dockerfile: fix CVE-2020-27350

---

test/e2e/framework/identityvalidator/identityvalidator_helpers.go

fix test failure in https://dev.azure.com/azure/aad-pod-identity/_build?definitionId=77&_a=summary

test: remove getIdentityValidatorArgs

---

website/content/en/changelog/_index.md
website/content/en/docs/Configure/aad_pod_identity_on_kubenet.md
website/content/en/docs/Getting started/installation.md

docs: add warning note to kubenet docs

---

Makefile
pkg/crd/crd.go
pkg/stats/stats.go
pkg/stats/stats_test.go

fix: fix typos in stats variables

---

Dockerfile

dockerfile: fix CVE-2020-29362, CVE-2020-29363, CVE-2020-29361

---

.github/PULL_REQUEST_TEMPLATE.md

chore: update github pr template

---

manifest_staging/charts/aad-pod-identity/templates/mic-exception.yaml

helm: skip MIC exception installation when using managed mode

---

manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
manifest_staging/deploy/infra/deployment-rbac.yaml
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/managed-mode-deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment-rbac.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml
test/e2e/block_instance_metadata_test.go

fix: drop all unnecessary root capabilities for NMI

---

pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

fix: check VM/VMSS state before PATCH calls

---

pkg/nmi/server/server.go
test/e2e/instance_metadata_test.go

Fixes #943. With the change introduced by this PR:
```
bash-5.0# curl -i http://169.254.169.254/doesnotexist
HTTP/1.1 404 Not Found
Content-Length: 1245
Content-Type: text/html
Date: Tue, 19 Jan 2021 16:30:46 GMT
Server: Microsoft-IIS/10.0
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
<div class="content-container"><fieldset>
<h2>404 - File or directory not found.</h2> …
```

fix: copy response header and status code to http.ResponseWriter

---

.pipelines/build-images.yml
.pipelines/scan-images.yml
Dockerfile
Makefile

feat: add arm64 build

---

pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

fix: check if provisioning state is not nil

---

pkg/auth/auth.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/crd/crd.go
pkg/k8s/client.go

fix: prevent errors from being overwritten by metric report function

---

website/content/en/docs/Getting started/role-assignment.md

Add extra assignment step required for self-managed clusters
Add self-managed clusters configuration docs
No code, only docs
Fixes #970

Add self-managed cluster configuration

---

website/content/en/docs/_index.md

docs: add note about system-assigned not supported

---

manifest_staging/charts/aad-pod-identity/templates/mic-deployment.yaml
test/e2e/framework/config.go
test/e2e/framework/helm/helm_helpers.go

flake: change mic sync interval from 1h to 30s

---

test/e2e/backward_compat_test.go

test: make backward compat test deterministic

---

pkg/apis/aadpodidentity/v1/conversion.go
pkg/apis/aadpodidentity/v1/conversion_test.go
pkg/auth/auth.go
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovider_test.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/crd/crd.go
pkg/crd/crd_test.go
pkg/k8s/client.go
pkg/k8s/fake.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/nmi/managed.go
pkg/nmi/standard.go
pkg/pod/pod.go
pkg/pod/pod_test.go

refactor: avoid named return when possible

---

manifest_staging/charts/aad-pod-identity/values.yaml
test/e2e/framework/identityvalidator/identityvalidator_helpers.go
website/content/en/docs/Best Practices/_index.md
website/content/en/docs/Troubleshooting/_index.md

Fixes #947
Fixes #969
Fixes #975

docs: improve documentations on multiple areas

---

manifest_staging/charts/aad-pod-identity/Chart.yaml
manifest_staging/charts/aad-pod-identity/README.md
manifest_staging/charts/aad-pod-identity/crds/crd.yaml
manifest_staging/charts/aad-pod-identity/templates/crds.yaml
manifest_staging/charts/aad-pod-identity/values.yaml

helm: remove helm 2 support

---

Makefile
go.mod
go.sum
pkg/nmi/server/server.go
pkg/nmi/server/server_test.go

- add case insensitive handler pattern
- fixes #1022

fix: add case insensitive handler pattern

---

.pipelines/pr.yml
.pipelines/templates/e2e-test.yml
.pipelines/templates/scan-images.yml
manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
manifest_staging/deploy/infra/deployment-rbac.yaml
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/managed-mode-deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment-rbac.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml

fix: add FileOrCreate to kubelet config file

---

.github/stale.yml

Add configuration for https://probot.github.io/apps/stale/

chore: add stale.yml

---

.pipelines/templates/unit-test.yml

upload token is not required: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token
- remove `CODECOV_TOKEN` env var as it's not required: https://docs.codecov.io/docs/about-the-codecov-bash-uploader#upload-token

ci: remove CODECOV_TOKEN env var

---

cmd/demo/main.go
go.mod
manifest_staging/deploy/demo/deployment.yaml

chore: remove vmss list from demo

---

Makefile

ci: create a make target to automate manifest promotion

---

pkg/apis/aadpodidentity/v1/conversion.go
pkg/apis/aadpodidentity/v1/register.go
pkg/apis/aadpodidentity/v1/types.go
pkg/crd/crd.go
test/e2e/framework/convenience.go

- Adds register.go to add crds to scheme
fixes #993 

feat: add register.go to add crds to scheme

---

manifest_staging/charts/aad-pod-identity/README.md
manifest_staging/charts/aad-pod-identity/templates/identities.yaml
manifest_staging/charts/aad-pod-identity/values.yaml

helm: ability to add AzureIdentities with the same name across different namespaces

---

website/content/en/docs/Configure/pod_identity_in_managed_mode.md
website/content/en/docs/Configure/standard_to_managed_mode.md
website/content/en/docs/Getting started/installation.md
website/content/en/docs/_index.md

docs: add standard to managed mode migration doc

---

website/content/en/docs/Configure/deploy_aad_pod_dedicated_sp.md
website/content/en/docs/Configure/deploy_in_openshift.md

fixes https://github.com/Azure/aad-pod-identity/issues/724

docs: add installation steps for Azure RedHat Openshift

---

website/content/en/changelog/_index.md
website/content/en/docs/_index.md

docs: fix managed mode URL

---

manifest_staging/charts/aad-pod-identity/templates/identities.yaml

helm: correct spec field for AzureIdentityBinding

---

Dockerfile

dockerfile: fix CVE-2021-3520

---

website/content/en/docs/Configure/feature_flags.md

docs: fix typo in feature flags

---

manifest_staging/deploy/demo/deployment.yaml

fix: use correct flags for demo image

---

cmd/mic/main.go
cmd/nmi/main.go
manifest_staging/charts/aad-pod-identity/README.md
manifest_staging/charts/aad-pod-identity/values.yaml
manifest_staging/deploy/infra/deployment-rbac.yaml
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/managed-mode-deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment-rbac.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml
pkg/mic/mic.go
test/e2e/framework/config.go
website/content/en/docs/Configure/feature_flags.md

- Enables scale features by default for NMI to reduce memory consumption and # of API calls by default
- Deprecates unused scale features flag in MIC. This flag will be removed in the release after `v1.8.1`

chore: enable scale features by default

---

Dockerfile

dockerfile: fix CVE-2021-33910

---

.github/stale.yml

stale bot is not working as intended. I am suspecting that it's misconfigured so trying the following stale.yml to see if it would trigger it.

chore: update .github/stale.yml

---

.github/workflows/stale.yml

Addresses https://github.com/Azure/aad-pod-identity/pull/1118#discussion_r675217150

fix: change stale bot trigger frequency to every day

---

.pipelines/pr.yml

- Adds website folder to exclude for PR trigger.

ci: exclude website changes for pr trigger

---

test/e2e/framework/config.go
test/e2e/framework/helm/helm_helpers.go
test/e2e/framework/iptables/iptables_helpers.go
test/e2e/instance_metadata_test.go

Add an option to test the nmi's metadata-header-required flag.

test: add an option to test metadata header

---

website/content/en/docs/Getting started/role-assignment.md

- Adds note about role assignments not required for managed mode.
fixes #1172 

docs: add note about managed mode in role assignments doc

---

Dockerfile
test/e2e/framework/iptables/iptables_helpers.go

chore: update debian-iptables to bullseye-v1.1.0

---

manifest_staging/charts/aad-pod-identity/templates/mic-deployment.yaml
manifest_staging/deploy/infra/deployment-rbac.yaml
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment-rbac.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml

security: enable readOnlyRootFilesystem for MIC

---

website/content/en/docs/Demo/standard_walkthrough.md
website/content/en/docs/Getting started/installation.md

docs: update release tag to v1.8.7 in docs

---

cmd/demo/main.go

- Removes `getTokenFromIMDS()` function in the demo
- `getTokenFromIMDS()` and `getTokenFromIMDSWithUserAssignedID()` are doing the exact same thing, so removing the additional function.

refactor: remove redundant token get from demo

---

Dockerfile

security: fix CVE-2018-25032

---

README.md
docs/RELEASE.md

docs: add release cadence

---

Dockerfile

security: fix CVE-2022-2068

---

Dockerfile

security: fix CVE-2021-4209

---

.pipelines/templates/scan-images.yml
go.mod
go.sum
test/e2e/go.mod
test/e2e/go.sum

```
┌─────────────────────────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────────────────────────┬───────────────────────────────────────────────────────────┐
│               Library               │ Vulnerability  │ Severity │         Installed Version          │           Fixed Version           │                           Title                           │
├─────────────────────────────────────┼────────────────┼──────────┼────────────────────────────────────┼───────────────────────────────────┼───────────────────────────────────────────────────────────┤
│ github.com/prometheus/client_golang │ CVE-2022-21698 │ HIGH     │ v1.11.0                            │ …
```

security: fix multiple CVEs

---

Dockerfile

resolves https://dev.azure.com/AzureContainerUpstream/AAD%20Pod%20Identity/_build/results?buildId=53247&view=logs&jobId=7e664a44-1d98-5348-601c-dff379a14ab5&j=7e664a44-1d98-5348-601c-dff379a14ab5&t=df0bac15-41b8-536a-5d4e-7c9def102aed

security: fix CVE-2021-46828

---

Dockerfile

security: fix CVE-2022-37434

---

Dockerfile

- Run `apt update && apt upgrade -y` to patch CVEs instead of managing individual packages.

chore: run apt update && apt upgrade -y in dockerfile

---

go.mod
go.sum
test/e2e/go.mod
test/e2e/go.sum

Fixes CVE-2022-27664
```bash
┌──────────────────┬────────────────┬──────────┬────────────────────────────────────┬───────────────────────────────────┬─────────────────────────────────────────────────────────────┐
│     Library      │ Vulnerability  │ Severity │         Installed Version          │           Fixed Version           │                            Title                            │
├──────────────────┼────────────────┼──────────┼────────────────────────────────────┼───────────────────────────────────┼─────────────────────────────────────────────────────────────┤
│ golang.org/x/net │ CVE-2022-27664 │ HIGH     │ v0.0.0-20211209124913-491a49abca63 │ 0.0.0-20220906165146-f3363e06e74c │ golang: …
```

security: fix CVE-2022-27664

---

.pipelines/pr.yml

ci: exclude .github path and README.md in tests

---

README.md
website/content/en/docs/_index.md

Adding deprecation notice to README

docs: add deprecation notice to readme

---

website/content/en/docs/Configure/standard_to_managed_mode.md

This PR is attempting to provide clarity based on this [issue](https://github.com/Azure/aad-pod-identity/issues/1347) by linking to a page detailed documentation! :) 

Link to full description of Standard and Managed modes

---

website/content/en/changelog/_index.md

docs: fix changelog for v1.8.12 release

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

update to github issues and pr templates for deprecation notice

---

docs/RELEASE.md

Update RELEASE.md to clarify September EOL
