Azure/aad-pod-identity

.circleci/config.yml
cmd/mic/main.go
pkg/cloudprovider/cloudprovider.go
pkg/config/azureconfig.go
pkg/mic/mic.go

- Rename mic.go in cmd to main.go for better debuggability.
- Add more logging for error paths.
- Move to yaml.unmarshal instead of json.unmarshal to circumvent the json parsing
issues caused by values such as 'True' (with caps T instead of all small true)
in the value fields of azure.json. This is similar to the azure.go in upstream k8s
code (parseConfig function).

Json parse fixes and improve debuggability

---

charts/aad-pod-identity/.helmignore
charts/aad-pod-identity/Chart.yaml
charts/aad-pod-identity/README.md
charts/aad-pod-identity/templates/crds.yaml
charts/aad-pod-identity/templates/identities.yaml
charts/aad-pod-identity/templates/infra.yaml
charts/aad-pod-identity/values.yaml

I've added a Helm chart that can help users bootstrap their Kubernetes cluster with the required resources. Details are included in the `README.md` - primarily meant to work with provided demo application as a way of demonstrating the functionality but can be used with custom apps. Supports both RBAC and non RBAC enabled clusters.

Added a sample Helm chart

---

Makefile

- Add GOOS and GOARCH so that only linux binaries are built.
- Reuse build targets in Makefile.

Add GOOS and GOARCH and reuse build targets in Makefile

---

pkg/cloudprovider/cloudprovidertest/cloudprovider_test_util.go
pkg/mic/mic.go
pkg/mic/mictest/mic_test.go
pkg/mic/mictest/mic_test_util.go
pkg/pod/podtest/pod_test_util.go

- Delete the assigned identity in case the vm id binding errors out.
- Raise events on failure to add or remove (#79).
- More UTs.

Error path deletion of assigned identity, raise events (#79)

---

deploy/infra/deployment-rbac.yaml

The current ClusterRole for RBAC-enabled clusters defines an extremely loose access privileges for the NMI service account. That service account has get and list verb across all api groups and resource types - including secrets from kube-system and user defined namespaces.
This PR restricts the access privileges to get/list of CustomResourceTypes defined by this service, plus pods.

Apply least privilege concept on NMI ClusterRole.

---

Gopkg.lock
deploy/infra/deployment-rbac.yaml
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovider_test.go
pkg/cloudprovider/cloudprovidertest/cloudprovider_test.go
pkg/cloudprovider/cloudprovidertest/cloudprovider_test_util.go
pkg/cloudprovider/identity.go
pkg/cloudprovider/identity_test.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/config/azureconfig.go
pkg/mic/mic.go
pkg/mic/mictest/mic_test.go
pkg/mic/mictest/mic_test_util.go
pkg/mic/node.go
pkg/pod/pod.go

This adds support for assigning identities to a VMSS when the underlying
cluster is using VMSS.
Note that identities get assigned to the entire VMSS.
This introduces a dependency on being able to list nodes from k8s so we can get the provider I, which allows us to determine (per node) if it is VMSS and what the real name of the resource we need to assign to is. This has the additional benefit in that it should be more robust than relying on the node names from k8s to match node names in Azure.
Closes #63

Add support for vmss

---

Makefile

Ensures that these binaries work regardless of what libraries they were
linked to at build time... e.g. build on Ubuntu (with glibc) and run on
Alpine (musl libc).
The main thing here is that if you import the `net` or the `archive/tar` packages
go will automatically switch from the defaul statically linked build to a
dynamically linked one.
The other part of this, if you are cross compiling (e.g. when building from macOS or Windows.. makefile specifies GOOS=linux) you will also get a static build even without this change. So whether or not the alpine images work highly depends on what platform the binaries are built on.
Fixes #131

Build statically linked binaries

---

README.md

I've found that if you choose a Managed Identity resource name that is different from the AzureIdentity name (aadpodidentity.yaml), the AzureIdentityBinding (aadpodidentitybinding.yaml) must reference the AzureIdentity name rather than the Managed Identity resource name.  Use of `<any-idname>` in the aadpodidentity.yaml example confused me in this scenario, so suggesting this change.

Fixes #137 - Remove ambiguity in naming requirements

---

charts/aad-pod-identity/templates/infra.yaml
deploy/demo/deployment.yaml
deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml

Address #146 by adding the linux node selector to all deployments of MIC.
Also added the selector to the demo deployment as the current image is also linux-specific.

Add linux node selector to MIC and demo deployments

---

pkg/crd/crd_test.go
pkg/mic/mic.go
pkg/mic/mic_test.go

The issue manifests when there are delete and add in the same cycle. Because we are running delete cycles first and then performing create cycles, the effect of create list adding itself to delete gets nullified there because create eventually gets done, right after the delete. Nevertheless this causes an unnecessary deletion and addition to the underlying vm identity. As for deletions take effect one at a time because only one 'real' to-be-deleted one gets appended in one cycle. Eventually the others also get deleted in subsequent cycles.
Inorder to repro the issue, the test adds two pods in one cycle, and then deletes both and and adds one more pod in the next cycle. With the bug - only one assigned id gets deleted in one cycle and the second one gets deleted in the second cycle. With …

Fixes the issue #141 raised for delete list appended with create list

---

azure-pipelines.yml
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/identity.go
pkg/cloudprovider/identity_test.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

Changes to ensure that identities already assigned to underlying VMs/VMSS instances are not assigned again in a single sync cycle. This brings down the assignment times in sceanrios where a single node(in case of VMA) or instances from a single VMSS are assigned the same identity as result of different pods matching their bindings. Brings down the time take to assign identities in #145.

Reduce identity assignment time 

---

pkg/k8s/client.go
pkg/k8s/client_test.go

Changes in reference to https://github.com/Azure/aad-pod-identity/issues/108
- Add retry sleep interval as an option
- Add UT for `GetPodName` and test retry logic

Add retry sleep interval as option

---

README.md
cmd/nmi/main.go
deploy/infra/deployment.yaml
pkg/nmi/iptables/iptables.go
pkg/nmi/server/server.go
test/common/k8s/pod/pod.go
test/e2e/aadpodidentity_test.go
test/e2e/template/busyboxds.yaml

resolves https://github.com/Azure/aad-pod-identity/issues/113
This will handle graceful shutdown of the pod, cleanup the ip table chain and rules that were inserted by NMI.

Handle iptables cleanup on uninstall

---

Makefile
cmd/mic/main.go
cmd/nmi/main.go
pkg/mic/mic.go
version/version.go

Acceptance criteria: As a user, I would like to see binary versions of NMI and MIC in the logs.
Fix a typo in the Makefile that caused the ARG for `NMI_VERSION` to be always empty. Add handling for `MIC_VERSION`.
These versions will show in the logs next time we build an image using `NMI_VERSION` and  `MIC_VERSION` args.
Fixes #207

Log binary versions

---

test/common/k8s/deploy/deploy.go
test/e2e/README.md
test/e2e/aadpodidentity_test.go
test/e2e/config/config.go
test/e2e/template/deployment-rbac.yaml
test/e2e/template/deployment.yaml

Based on #129 from @pjbgf 
The former E2E tests were being executed against the publicly available docker images, instead of using the images generated locally and published into custom container registry. Making it easier for new contributors to support this project.
New ENV config variables:
REGISTRY 
NMI_VERSION
MIC_VERSION
IDENTITY_VALIDATOR_VERSION
Once the environment variables are set, changes can be built and tested in a cluster with:
make build && make image && make push && make e2e

Update E2E to run tests based on generated images 

---

test/common/k8s/deploy/deploy.go
test/e2e/aadpodidentity_test.go
test/e2e/template/deployment-rbac.yaml

This is needed because `mic:1.3` and `nmi:1.4` required the `- mic` and `- nmi` args. I'll remove these during next release.

fix deployment template for e2e

---

pkg/apis/aadpodidentity/v1/types.go
pkg/crd/crd.go
pkg/pod/pod.go

Two main items:
- Utilize the client cache for listing of CRDs
- Avoids going to API Server for every list call.
- Resolve the part of #182 related to the API Server calls.
- Avoid calling sync loop at every pod update. Only call where there is a change in scheduled node name.

List CRDs via cache and avoid extra work on pod update

---

CONTRIBUTING.md
README.md

This tries to make the project README more concise and approachable for someone who isn't very familiar with AAD Pod Identity (like me).
* Adds badges for go docs and the Go Report Card (A+)
* Sorts the sections so **Getting Started** is first
* Puts the **Contributing** section in a separate CONTRIBUTING.md document as recommended by GitHub's [community guidelines](https://github.com/Azure/aad-pod-identity/community)
* Moves the **Design**, **Tutorial**, **Debugging**, and **Contributing** sections into links in a **What To Do Next?** section
* Adds an example of the `az identity create` output
* Lots of markdown linter cleanup
* Moves markdown target links to the bottom for DRY and readability
* Tries to streamline as much of the writing as possible
* Moves **Uninstall Notes** to the …

docs: tighten and organize README.md

---

pkg/crd/crd.go

Fix the lite CRDClient to include initialization of the AzureAssignedID cache list watcher.

Fix the lite CRD client to include assigned identity watcher

---

cmd/demo/main.go
pkg/nmi/server/server.go
test/e2e/aadpodidentity_test.go

Buffers a channel in NMI startup so `os.Signal` won't be missed during a (small) window, and handles some ignored error values as pointed out by the `staticcheck` linter.
See https://golang.org/pkg/os/signal/#Notify for an explanation of why `os.Signal` channels should be buffered.

fix: use buffered channel for os.Signal and other cleanup

---

Makefile
test/common/k8s/azureassignedidentity/azureassignedidentity.go
test/common/k8s/daemonset/daemonset.go
test/common/k8s/deploy/deploy.go
test/common/k8s/infra/infra.go
test/common/k8s/pod/pod.go
test/e2e/aadpodidentity_test.go

- Make e2e deterministic. Remove sleep and wait until requirements are met.
- Fix tests
- Resolve panics in e2e
- Skip known failing test
resolves https://github.com/Azure/aad-pod-identity/issues/213

Make e2e tests deterministic

---

Makefile
pkg/k8s/client.go
pkg/k8s/client_test.go

Use cache while listing pod in NMI calls.
Complete the fixes for #182
Minor fix for Makefile.
Currently the NMI calls to get the pod info would always contact the api-server. This PR ensures that those calls can go through the go-client caches thus reducing api-server load.
#182 
Undergoing e2e and cleanup, but ready for first round of review.

Use cache while listing pod in NMI calls.

---

cmd/demo/main.go
pkg/apis/aadpodidentity/v1/utils.go
pkg/cloudprovider/cloudprovider_test.go
pkg/crd/crd_test.go
pkg/mic/mic_test.go
pkg/nmi/server/server.go
pkg/pod/pod_test.go
pkg/stats/stats.go
pkg/stats/stats_test.go
test/e2e/identityvalidator/identityvalidator.go

Fixes some of the misspellings and style warnings pointed out by `golint`, `gosimple`, and `go vet`.

style: clean up some linter warnings

---

pkg/cloudprovider/cloudprovider.go

The error from `adal.NewOAuthConfig` was ignored, so the subsequent error handling block could never be entered since it was comparing the previous `err` to `nil` again. I also made the handling consistent with the rest of the function.

fix: handle new OAuthConfig error consistently

---

pkg/cloudprovider/cloudprovider.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/mic/vmss.go

Before this change, an identity on a VMSS node may be deleted from the
VMSS even if it's used on another node in the VMSS.
This makes the check for identity in use vmss aware since identities on
a vmss are managed for the entire vmss, not just a single node in the
vmss.
Fixes #198

Fix vmss identity deletion for ID in use

---

Makefile
pkg/cloudprovider/vm.go

During the removal of user assigned identity from a node with system assigned identity, we were not making the identity list as nil. This was resulting in the cloud call to fail with the error saying that identity list should be nil. This PR makes the identity list nil (when only system assigned identity should be left on the node) before calling the cloud call to remove the identities.
#214 

Fix removal of user assigned identity from nodes with system assigned 

---

pkg/k8s/client.go

`NewListWatchFromClient` doesn't respect the fieldselector options provided to filter pods. Instead we'll create `NewFilteredListWatchFromClient` with empty options modifier. In this case ListWatch will use the options we provide during list.
Fixes https://github.com/Azure/aad-pod-identity/issues/260

Change to filtered list watch to fix fieldselector

---

pkg/mic/mic.go
pkg/mic/mic_test.go

- Adds some locking around concurrently accessed objects.
- Make sure sync is not called concurrently
- Make tests wait for sync to exit (prevent race with stats package)
Fixes #258 

Fix mic test data races

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovider_test.go
pkg/cloudprovider/identity.go
pkg/cloudprovider/identity_test.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/crd/crd.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/stats/stats.go
test/common/k8s/azureassignedidentity/azureassignedidentity.go
test/common/k8s/infra/infra.go
test/e2e/aadpodidentity_test.go
test/e2e/template/deployment.yaml

resolves 
https://github.com/Azure/aad-pod-identity/issues/145
https://github.com/Azure/aad-pod-identity/issues/181
https://github.com/Azure/aad-pod-identity/issues/217
- Batch process id assignments to node on each sync cycle (pooling delete and add ids, issuing one CreateOrUpdate call for each sync cycle)
- Reduces identity assignment for 44 pods from 29m to ~3m
Add states to the assigned identities
1. Created - assigned identity will be in created state when the crd is created.
2. Assigned - once the identity has been successfully assigned to underlying node, the state of the assigned identity will be changed to Assigned.
3. Unassigned - the assigned identity will be in this state when the identity has been successfully removed from the underlying node.
**Note**
1. Assigned identities …

Performance  Improvement - reduce identity assignment time

---

pkg/k8s/client.go

In pod retry the object returned from listing was used to cast even when error was returned. This PR
fixes this issue. The retry call has been refactored to account for other error conditions and simplify
the usage. This PR introduces getPodList call and then a retry call built on top of that.
Fix the nil cast panic in case of error return from Listpod.

Fix the nil cast on error for podlist and refactor pod retry call

---

pkg/cloudprovider/identity.go
pkg/cloudprovider/identity_test.go

MIC fails when trying to compare same identity but with different cases for resource groups `resourceGroups` | `resourcegroups` in the resourceID format. This results in error when trying to assign the identity which already exists. This change will ensure we validate the identities case insensitively.
https://github.com/Azure/aad-pod-identity/issues/269

Handle case sensitive id check

---

Makefile
cmd/mic/main.go
pkg/apis/aadpodidentity/v1/types.go
pkg/crd/crd.go
pkg/k8s/client.go
pkg/k8s/fake.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/nmi/server/server.go
pkg/nmi/server/server_test.go
test/e2e/aadpodidentity_test.go
test/e2e/template/deployment-rbac.yaml

- Wrap list pod ids call with retries
- Filter assigned ids based on state in NMI
- Change the status code to `404` instead of `403` when no valid assigned ids found after retries. 
- Add a ticker to periodically run sync cycle to reconcile any crds that are in error state. This is required because if no pod events are generated, then the sync loop will never get triggered to resync.
- Make the sync retry interval configurable
fixes https://github.com/Azure/aad-pod-identity/issues/257

NMI retries and ticker for periodic sync reconcile

---

cmd/nmi/main.go
docs/readmes/README.msi.md
pkg/auth/auth.go
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/vmss.go
pkg/config/azureconfig.go
pkg/k8s/client.go
pkg/k8s/client_test.go
pkg/k8s/fake.go
pkg/nmi/server/server.go

This PR adds the capability for MIC to look at azure.json or environment variables
to determine whether the system assigned or user assigned MSI has to be used for accessing
azure resources. The MIC requests for token based on MSI. Also contains changes in NMI to determine if the request is originating from an MIC replicaset. If so, NMI directly generates the tokens instead of looking up the azure assigned identity for the pod-binding match.
Adds ability for MIC to authenticate using system assigned/user assigned MSI.
Resolves the item in #261.
TODO: run the e2e on system assigned identity cluster.

Adds support for MIC to authenticate with azure using system assigned/user assigned MSI

---

test/common/azure/azure.go
test/common/k8s/deploy/deploy.go
test/common/k8s/infra/infra.go
test/common/k8s/node/node.go
test/e2e/aadpodidentity_test.go
test/e2e/template/deployment.yaml

Adds an e2e test testing deletion of vmss identities.
I have not run this test yet and am not particularly familiar with Ginkgo. Be kind 👼 🙇 
Posting this for early input.

Add e2e test for vmss deletion

---

pkg/mic/mic.go
test/common/azure/azure.go
test/e2e/aadpodidentity_test.go

This feature is to parallel process cloud API calls to node for identity assignment and removal.
e2e tests in master branch are broken. This PR fixes the e2e tests.

Parallelize node cloud calls

---

cmd/mic/main.go
deploy/infra/master/replicaset/deployment-rbac.yaml
deploy/infra/master/replicaset/deployment.yaml
pkg/mic/mic.go
test/e2e/template/deployment-rbac.yaml

Add leader election code to MIC to run it as ReplicaSet with multiple replicas which can come up and continue in case of a failure of the active MIC. Also added are deployment yamls which configures the ReplicaSet appropriately under deploy/master/replicaset.
TODO: 
1. Add tests in e2e

Add leader election code to MIC

---

cmd/mic/main.go
cmd/nmi/main.go
deploy/infra/master/replicaset/deployment-rbac.yaml
deploy/infra/master/replicaset/deployment.yaml
pkg/mic/mic.go
pkg/nmi/server/server.go
pkg/probes/probes.go
test/common/k8s/infra/infra.go
test/e2e/aadpodidentity_test.go
test/e2e/template/deployment-rbac-old.yaml
test/e2e/template/deployment-rbac.yaml

- Add liveliness at /healthz endpoint for MIC and NMI at 8080 by default.
~~- Add readiness at /ready endpoint for MIC and NMI at 8080 by default.~~
~~- Both liveness and readiness probe return back 200 okay as soon as they are activated from the current run.~~
- The liveliness probe provides "Active" or "Not Active" status as per the state of the component. In case of MIC if the given instance is the elected leader then "Active" string is presented in the /healthz endpoint. For NMI it would show "Active" as soon as the iptables are put in place. 
- Fix the NMI iptables to run instantly instead of waiting for the first ticker instance.
#288 

Liveness probe

---

pkg/nmi/server/server.go

Introduces msiResponse struct to marshal token in
a format that matches the underlying metadata
endpoint more closely. The `expires_in`, `expires_on`,
and `not_before` fields are originally provided as
quoted strings.
Increases compatibility with existing service images
built on older versions of adal client libraries.
Fixes #303
Fixes #275

Marshalling token response in original format

---

.gitignore
Makefile
test/e2e/aadpodidentity_test.go

- This PR adds the ability to collect the logs, events, endpoint and pod state, in case of a test failure. 
- Also removed is ginkgo fail fast so that tests can continue if one of them fails.

E2e - collect info on test failure

---

test/common/azure/azure.go
test/common/k8s/azureassignedidentity/azureassignedidentity.go
test/common/k8s/daemonset/daemonset.go
test/common/k8s/deploy/deploy.go
test/e2e/aadpodidentity_test.go
test/e2e/config/config.go
test/e2e/setup.sh

- Enable e2e on System assigned MSI+VMSS single nodepool cluster
- Increase timeout for VMSS
- Make retry generic and support it for set-policy in setup.sh
TODO: Add the SYSTEM_MSI_CLUSTER setting step in e2e README

VMSS e2e changes and System MSI cluster support

---

cmd/nmi/main.go
pkg/nmi/server/server.go

Update the NMI retry interval to 80s for CREATED state and additional 20s for ASSIGNED state. This done because identity assignment on VMSS takes ~35-37s on average.

update nmi retry interval

---

Dockerfile
test/e2e/template/busyboxds.yaml

Update base alpine image to `3.10.1`. That is the latest available tag with no vulnerabilities.

Update base alpine image to 3.10.1

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/mic/mic.go
test/common/azure/azure.go
test/e2e/aadpodidentity_test.go

When the last underlying identity is deleted from the node, the deletion of assigned identity fails because the resource type is not set during the `CreateOrUpdate` call. This PR ensures when the identity list is nil, the resource type is set to None.
Adds e2e test to valid the scenario.
Fixes https://github.com/Azure/aad-pod-identity/issues/313

Fix assigned id deletion when no identity exists

---

deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml

Without explicit strategy set, it defaults to `OnDelete` which means
`nmi` pods will be updated only when they are terminated, which doesn't
happen often obviously and it's quite unpredictable.
With this change, `kubectl apply` correctly upgrades and restarts all
the components when new verison is applied.
none

Change 'updateStrategy' for nmi DaemonSet to `RollingUpdate`

---

pkg/auth/auth.go

Before the fix, append happened each time
`GetServicePrincipalTokenFromMSIWithUserAssignedID` was called, which
was blowing up HTTP header size (or header value size).
This also updates adal UserAgent for any call from this library, not
only for the one mentioned above.
Fixes a bug, makes UA header consistent.
Fixes: #332
(not tested yet)

Append NMI version to the `User-Agent` for adal only once

---

pkg/nmi/server/server.go

As aad-pod-identity moved to new adal libraries, the usage of older libraries had become incompatible (due to backward combat issues introduced with https://github.com/Azure/go-autorest/pull/326). With the PR #306 backward compatibility was added in paths where applications fetch tokens. The host handler path which is used by kevvault flex volume also needs similar fixes. This PR fixes that path. 
#336 
Ran 15 of 17 Specs in 3684.931 seconds
SUCCESS! -- 15 Passed | 0 Failed | 0 Pending | 2 Skipped
--- PASS: TestAADPodIdentity (3684.93s)
PASS
ok      github.com/Azure/aad-pod-identity/test/e2e      3684.958s

Fix the token backward compat in host based token fetching

---

pkg/stats/stats.go
pkg/stats/stats_test.go

With parallel node updates there are code paths which updates these stats concurrently.
These changes add lock around stats and UT corresponding to that.

Stats locks and tests

---

pkg/k8s/client_test.go

When fake rest client is used, the UT eventually hits the issue in https://github.com/kubernetes/client-go/issues/352. This PR uses the rest client from the fake package and also adds the corresponding HTTP clients to return back the pods to simulate the original package behavior.
Fixes #243 

Re-enable the UTs by using fake rest client

---

cmd/mic/main.go
pkg/k8s/client.go

Add user-agent to kube-api calls. 
Fixes https://github.com/Azure/aad-pod-identity/issues/352
Sample output from grafana -
```
{client="aad-pod-identity/MIC/0.0.0-dev/6f597c3/2019-08-21-06:53",resource="azureassignedidentities",verb="CREATE"}
{client="aad-pod-identity/MIC/0.0.0-dev/6f597c3/2019-08-21-06:53",resource="azureidentities",verb="LIST"}
{client="aad-pod-identity/NMI/0.0.0-dev/6f597c3/2019-08-21-06:52",resource="azureassignedidentities",verb="LIST"}
```

add user agent to kube-api calls

---

pkg/nmi/server/server.go

Proposed fix for https://github.com/Azure/aad-pod-identity/issues/340
Rest Clients expects the content type to be application/json
https://github.com/Azure/aad-pod-identity/issues/340
Fixes
https://github.com/Azure/aad-pod-identity/issues/340
https://github.com/Azure/aad-pod-identity/issues/368

Set Content-Type on token response

---

cmd/nmi/main.go
pkg/crd/crd.go
pkg/k8s/client.go
pkg/k8s/fake.go
pkg/logger/logger.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/mic/utils.go
pkg/nmi/server/utils.go
pkg/stats/stats.go

Delete assigned identities for the node, when node no longer exists.
Fixes https://github.com/Azure/aad-pod-identity/issues/366
Pending testing + running e2e

Clean up assigned identities if node not found

---

deploy/infra/rc/deployment-rbac.yaml
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovider_test.go
pkg/mic/mic.go
pkg/mic/vmss.go
test/e2e/aadpodidentity_test.go

Update identity in vmss only once as identity is across all nodes in vmss and not just single node.
Fixes https://github.com/Azure/aad-pod-identity/issues/361

update identity in vmss only once

---

pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/stats/stats_test.go

In forcenamespaced configuration multiple bindings or identities could exists with the same name in different namespaces. The last binding which matched was used to create the assigned identity representing current state. This PR fixes the issue by using the right bindings and identities.
The map used for handling of identities did not consider the namespace. This PR changes the key of the map to a combination of namespace and name of the identity.

Fix namespaced multiple binding/identity handling and verbose logs

---

cmd/mic/main.go
cmd/nmi/main.go
go.mod
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/crd/crd.go
pkg/k8s/client.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/stats/stats.go
test/common/k8s/infra/infra.go
test/e2e/aadpodidentity_test.go
test/e2e/config/config.go
test/e2e/template/deployment-rbac.yaml

- Pod informer modified to use node based listing in NMI
- Add ability to enable pprof profiling.
- Add labels to AzureAssignedIdentity which indicates the nodename, pod name and pod namespace. This is used to tune the list/watches in NMI. NMI in 'enableScaleFeatures' mode will list/watch based on nodename in the label. This reduces the payload passed between the etcd, api-server and NMI. With this we can scale to large number of nodes.
- `CREATE/UPDATE/DELETE` operations for each node/VMSS in parallel based on 'createDeleteBatch' parameter.
- Parallelize the create/delete of AzureAssignedIdentity operations for individual VMSS.
- Cache sync fixes.
- Fix to not call CacheSync in every cycle to avoid go-client thread leak issue.
- Add flags for setting `QPS`, `burst` …

improvements for scale

---

cmd/mic/main.go
cmd/nmi/main.go
go.mod
pkg/crd/crd.go
pkg/k8s/client.go
pkg/mic/mic.go
pkg/mic/mic_test.go
test/common/k8s/infra/infra.go
test/e2e/aadpodidentity_test.go
test/e2e/config/config.go
test/e2e/template/deployment-rbac.yaml

- Add ability to enable pprof profiling.
-  Add labels to AzureAssignedIdentity which indicates the nodename, pod name and pod namespace. This is used to tune the list/watches in NMI. NMI in 'enableScaleFeatures' mode will list/watch based on nodename in the lable. This reduces the payload passed between the etcd, api-server and NMI. With this we can scale to large number of nodes.     
-  Create/Delete operations for each node/VMSS based on the parallelism set by 'createDeleteBatch' parameter.
-  Parallelize the create/delete of AzureAssignedIdentity operations for individual VMSS. 
- Cache sync fixes.
- Fix to not call CacheSync in every cycle to avoid go-client thread leak issue.

Node filtered listing for pod/AzureAssignedIdentity, enable pprof, and misc cache sync fixes

---

pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

Remove unused GET in CreateOrUpdate

---

charts/aad-pod-identity/templates/mic-deployment.yaml
charts/aad-pod-identity/templates/nmi-daemonset.yaml

Kubernetes 1.16 [removes](https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/) API version `extensions/v1beta1` for `Deployment` and `DaemonSet` (in addition to other resources as well).
This PR fixes the existing usages.
N/A

Remove deprecated API version usages

---

pkg/nmi/server/server.go

- Reduces log noise from retries.

reduce log verbosity for debug log

---

cmd/mic/main.go
pkg/mic/mic.go
pkg/mic/mic_test.go
test/e2e/aadpodidentity_test.go

With the change for whitelisting identities - https://github.com/Azure/aad-pod-identity/pull/431, non-immutable identities are no longer being cleaned up as expected. 
This PR fixes the identity removal from non-immutable identities and also performs the check for immutable/non-immutable right at the start.

fix identity removal

---

Dockerfile

3.10.1 has a high severity vulnerability being raised on our CSP. it's good to be on latest anyway.
https://github.com/alpinelinux/docker-alpine/issues/34
NA

Moving to latest Alpine

---

test/e2e/template/busyboxds.yaml

Follow up to this PR -https://github.com/Azure/aad-pod-identity/pull/446
Bumping the alpine image used in e2e tests to `3.10.3`

Update alpine image used in tests

---

pkg/nmi/server/server.go

Validates if the `resource` parameter exists in the token request. This validation is currently done in the sdk and we are introducing the change in order to mimic the exact same error response code that IMDS would send for such a scenario.
Request without `resource` param while talking directly also returns an error and `400` response code -
```
body {"error":"invalid_request","error_description":"Required query variable 'resource' is missing"}
Response status: 400 Bad Request
```
With this change we will be more aligned with what a user would typically see while taking to IMDS without pod-identity.

validate resource param exists

---

pkg/nmi/iptables/iptables.go

Fixes an issues where len of rules returned from `iptables -t nat -S aad-metadata` is 3 instead of 2.
```
root@k8s-agentpool1-24487553-vmss00000Y:/# iptables -t nat -S aad-metadata
-N aad-metadata
-A aad-metadata ! -s 127.0.0.1/32 -d 169.254.169.254/32 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.240.3.134:2579
-A aad-metadata -j RETURN
```

Update rules len check for iptables

---

charts/aad-pod-identity/templates/nmi-daemonset.yaml
deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml
deploy/infra/noazurejson/deployment-rbac.yaml
deploy/infra/noazurejson/deployment.yaml
deploy/infra/rc/deployment-rbac.yaml
deploy/infra/rc/deployment.yaml
test/e2e/template/deployment-rbac-old.yaml
test/e2e/template/deployment-rbac.yaml

Remove `kubernetes.io/cluster-service: "true"` label which is typically used for addons and has been deprecated since 1.11
partially resolves https://github.com/Azure/aad-pod-identity/issues/471

remove cluster service label

---

charts/aad-pod-identity/templates/_helper.tpl
charts/aad-pod-identity/templates/mic-deployment.yaml
charts/aad-pod-identity/templates/nmi-daemonset.yaml

The helm chart is currently broken when upgrading as it includes the helm chart value in the resource standard labels and these are used in deployment and daemonset `selector`.  Selectors are now immutable.
As suggested by twendt in #502, this separates the variable labels from static ones that are used in selectors.
Fixes #502 
Fixes #507
Users who have already deployed a 1.5.x chart will have to uninstall aad-pod-identity before applying this chart as they will already have the `helm.sh/chart` label in the selectors. This is a one-off requirement and as a permanent forward-fix this PR is good.

Add selectors as separate include

---

pkg/cloudprovider/identity.go
pkg/cloudprovider/identity_test.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

In case of VMSS, if no identities exist the RP assumes the identity type to be `UserAssigned` if not explicitly set. This is not the case for VMAS. So this PR explicitly sets the type based on the current resource identity type.

set resource identity type explicitly

---

pkg/mic/mic.go

Removes the `podname` and `podnamespace` label in the `AzureAssignedIdentity` which are redundant (podname and podnamespace already exist in spec). This fixes the issue where pod name is > 63 chars. `metadata.Labels` have a [63 char limit](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) which results in failure while creating `AzureAssignedIdentity` for pod names > 63 chars
fixes https://github.com/Azure/aad-pod-identity/issues/508

remove pod name label

---

pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/utils/utils.go
pkg/utils/utils_test.go

Validate `ResourceID` from `AzureIdentity` and skip processing `AzureIdentity` if resource id is not valid. This prevents `LinkedInvalidPropertyId` errors during vm/vmss `UPDATE` calls with invalid identities. 
fixes https://github.com/Azure/aad-pod-identity/issues/466

add validation for resource id

---

cmd/nmi/main.go
pkg/apis/aadpodidentity/v1/conversion.go
pkg/apis/aadpodidentity/v1/conversion_test.go

- Checks if the `AzureIdentityRef` and `AzureBindingRef` exists before conversion to prevent accessing nil pointer.

add nil check during conversion

---

README.md

solves: #467
Prescribe add-pod-indentity installation in `kube-system`, otherwise it might fail trying to contact the AKS Api Server
fixes #467

prescribe aad-pod-identity installation in kube-system

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/crd/crd.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/stats/stats.go
test/common/k8s/azureidentity/azureidentity.go
test/e2e/aadpodidentity_test.go
test/e2e/template/aadpodidentity.yaml

- Adds code path to update azure assigned identity when azure identity is updated in place
- Ensures old identity is deleted and new updated identity is assigned
- Adds e2e test to test update path
fixes https://github.com/Azure/aad-pod-identity/issues/510, fixes https://github.com/Azure/aad-pod-identity/issues/504

fix updating assigned identity when azure identity updated

---

test/common/azure/azure.go
test/e2e/aadpodidentity_test.go

#579 introduced `IDENTITY_RESOURCE_GROUP` and `CLUSTER_RESOURCE_GROUP` as part of the envconfig for e2e test, so we can no longer assume that the user-assigned identity is within the same resource group as the cluster. Instead of using the name of the user-assigned identity to identify them, we started using the resource ID obtained from `az identity show -g <IdentityResourceGroup> -n <IdentityName>`.
The resource ID obtained from `az identity show` has a `resourcegroup` part of it instead of `resourceGroup` for some unknown reasons. It caused `should not alter the user assigned identity on VM after AAD pod identity is created and deleted` test case to fail since it constructs on a map of user-assigned identity where the key is the resource ID of the identity and …

fix: fix e2e test regression caused by #579

---

pkg/crd/crd.go
pkg/crd/crd_test.go
pkg/mic/mic.go
pkg/mic/mic_test.go

- Adds finalizer to `AzureAssignedIdentity`
- ensures, the `AzureAssignedIdentity` is only deleted after the identity is successfully un-assigned from the node.
- ensures identities are cleaned up when namespace is deleted.
fixes https://github.com/Azure/aad-pod-identity/issues/533

feat: add finalizer for assigned identity

---

go.mod
go.sum
pkg/cloudprovider/cloudprovider.go
pkg/filewatcher/filewatcher.go
pkg/filewatcher/filewatcher_test.go
pkg/mic/mic.go

Re-initialize MIC cloud client when cloud config is updated so that it has the latest credentials to perform cloud operations.
Fixes #523.
For aks-engine cluster, ssh into the node to modify `/etc/kubernetes/azure.json`. It's known that vim does not trigger a WRITE event to fsnotify. You can use other text editors like nano to test.
For AKS cluster, use `az aks update-credentials`.

feat: re-initialize MIC cloud client when cloud config is updated

---

.pipelines/nightly.yml
.pipelines/pr.yml

Set up nightly build and test against master. I will need to point the current pipeline YAML from `azure-pipelines.yml` to `pr.yml` after this is merged.

ci: set up nightly build and test against master

---

deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml
deploy/infra/noazurejson/deployment-rbac.yaml
deploy/infra/noazurejson/deployment.yaml

This exception is already part of helm charts. Adding the default `PodIdentityException` for MIC, so that token requests for MIC aren't intercepted by NMI when deployed in non default namespace.
fixes https://github.com/Azure/aad-pod-identity/issues/610

add mic pod exception to deployment

---

README.md
deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml
deploy/infra/mic-exception.yaml
deploy/infra/noazurejson/deployment-rbac.yaml
deploy/infra/noazurejson/deployment.yaml

kubectl apply -f `<multi yaml file>` is not processed in order. This could mean in some scenarios the `AzurePodIdentityException` is applied first before the CRD is deployed. With this PR, we are moving the `AzurePodIdentityException` to a separate yaml, so users can apply it after deploying the infra components.
cc @dapolloxp 

Move exception to a different yaml

---

cmd/mic/main.go
docs/readmes/README.troubleshooting.md
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovider_test.go
pkg/cloudprovider/identity.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vm_test.go
pkg/cloudprovider/vmss.go
pkg/cloudprovider/vmss_test.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/retry/retry.go
pkg/retry/retry_test.go
test/common/k8s/azureassignedidentity/azureassignedidentity.go
test/common/k8s/azureidentity/azureidentity.go
test/e2e/aadpodidentity_test.go

Attempts to extract erroneous user-assigned identities from ARM error message and remove them from the identity update list before retrying.
Fixes #599.
Steps I took to test:
1. Create two AzureIdentities and AzureIdentityBindings, one with valid resource ID and one with resource ID that does not exist
2. Create a pod that consumes the two AzureIdentities
3. Check that there are two AzureAssignedIdentities created. The one with valid resource ID should be in "Assigned" state and the other should be in "Created" state.
3. Check that one of the user-assigned identities is assigned correctly to the underlying node on Azure, and the other one isn't.

feat: make update user msi calls retriable

---

.pipelines/pr.yml
README.md

With nightly build & test setup against master branch, there is no need to run CI when a PR is merged to master.

ci: disable CI against master branch when merging PRs

---

pkg/auth/auth.go
pkg/nmi/server/server.go

- Return `404` for both scenarios - No AzureAssignedIdentity found in `CREATED` or `ASSIGNED` state
When `az login --identity -u <clientID>` command is invoked, the CLI adds the clientID in `client_id` header. When it receives a `400` back, it retries the request with the clientID in the `object_id` header. In this scenario, aad-pod-identity will return the token for the first AzureIdentity that matches the pod as `client_id` is empty. This is not wrong, but could confuse the user as they are not aware of the CLI internals.  The token they receive would be for a different identity.
Instead when a `404` is returned, then CLI still retries consistently with the `client_id` header which is the correct behavior. 

change to 404 instead if no azure identity found

---

test/e2e/aadpodidentity_test.go
test/e2e/identityvalidator/identityvalidator.go

Sets default context timeout to `150s` in the validate tests to ensure the tests completes in acceptable time and also tests running negative scenarios don't run for too long.

chore: set context timeout for tests

---

README.md
charts/aad-pod-identity/templates/mic-exception.yaml
deploy/infra/mic-exception.yaml

- Adds a default `AzurePodIdentityException` for AKS add-ons in kube-system namespace. This will ensure when aad-pod-identity is deployed on a managed identity cluster, it allows token requests from add-ons in kube-system namespace without pod-identity validation.

chore: add aks add-on exception in kube-system

---

charts/aad-pod-identity/values.yaml
deploy/demo/deployment.yaml
deploy/infra/deployment-rbac.yaml
deploy/infra/deployment.yaml
deploy/infra/managed-mode-deployment.yaml
deploy/infra/noazurejson/deployment-rbac.yaml
deploy/infra/noazurejson/deployment.yaml
test/e2e/template/busyboxds.yaml
test/e2e/template/deployment-rbac-old.yaml
test/e2e/template/deployment-rbac.yaml

Replacing deprecated labels `beta.kubernetes.io/os` with `kubernetes.io/os` which is GA since 1.14. `beta.kubernetes.io/os` will be deprecated in upcoming release 1.19.
fixes https://github.com/Azure/aad-pod-identity/issues/645

update node selector label to kubernetes.io/os

---

README.md
charts/aad-pod-identity/README.md
charts/aad-pod-identity/templates/crds.yaml
charts/aad-pod-identity/values.yaml

Disable crd-install when using Helm 3.
Fixes #626

chore: disable crd-install when using Helm 3

---

test/e2e_new/disruptive_test.go
test/e2e_new/framework/azure/azure_helpers.go
test/e2e_new/framework/azureidentity/azureidentity_helpers.go
test/e2e_new/framework/identityvalidator/identityvalidator_helpers.go
test/e2e_new/framework/interfaces.go
test/e2e_new/framework/iptables/iptables_helpers.go
test/e2e_new/identity_exception_test.go
test/e2e_new/init_containers_test.go
test/e2e_new/invalid_identities_test.go
test/e2e_new/liveness_probe_test.go
test/e2e_new/multiple_identities_test.go
test/e2e_new/single_identity_test.go

Follow-up PR for #650.
Converted the following test cases from old to new framework:
`should assign the valid identity to the node when batch assigning identities that contain invalid identities`
`should not unassign existing identity if we assign invalid identities`
`should pass identity validation with correct identity and fail with wrong identity`
`should update AzureAssignedIdentity and when AzureIdentity fields are updated`
`should assign identity with init container`
ref: #586, #657

test: convert e2e test cases from old to new framework (part 2)

---

charts/aad-pod-identity/templates/nmi-daemonset.yaml
test/e2e_new/backward_compat_test.go
test/e2e_new/disruptive_test.go
test/e2e_new/framework/azureidentity/azureidentity_helpers.go
test/e2e_new/framework/azureidentitybinding/azureidentitybinding_helpers.go
test/e2e_new/framework/config.go
test/e2e_new/framework/exec/kubectl.go
test/e2e_new/framework/helm/helm_helpers.go
test/e2e_new/framework/identityvalidator/identityvalidator_helpers.go
test/e2e_new/framework/iptables/iptables_helpers.go
test/e2e_new/framework/mic/mic_helpers.go
test/e2e_new/liveness_probe_test.go

Follow-up PR for #662.
Converted the following test cases from old to new framework:
`should pass the identity validation even when MIC leader is changed`
`should pass liveness probe test`
`should be backward compatible with old and new version of MIC and NMI`
ref: #586, #657

test: convert e2e test cases from old to new framework (part 4)

---

charts/aad-pod-identity/templates/mic-deployment.yaml

Remove unused /etc/kubernetes/certs directory as this is sensitive information

Remove unused cert volumes from mic deployment

---

cmd/demo/main.go
cmd/mic/main.go
cmd/nmi/main.go
cmd/simple/main.go
pkg/auth/auth.go
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/crd/crd.go
pkg/filewatcher/filewatcher.go
pkg/k8s/client.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/metrics/prometheus_exporter.go
pkg/mic/mic.go
pkg/mic/mic_test.go
pkg/nmi/iptables/iptables.go
pkg/nmi/managed.go
pkg/nmi/nmi.go
pkg/nmi/server/server.go
pkg/nmi/standard.go
pkg/pod/pod.go
pkg/pod/pod_test.go
pkg/probes/probes.go
pkg/stats/stats.go
pkg/utils/utils.go
test/e2e/identityvalidator/identityvalidator.go

Logging and returning the error are both considered error handling. We should only choose one method to handle the error but not both.
Fixes #604.

refactor: better error messages and handling

---

test/e2e/framework/azure/vm_manager.go
test/e2e/framework/azure/vmss_manager.go

The case of the `resourceID` returned from the `GET` can differ from the `resourceID` we construct. It's best to check if the identity exists, and if does skip the assignment. This should resolve the flakes we are seeing with assigning identity during the e2e runs.

fix: check if identity exists before assign in e2e

---

test/e2e/disruptive_test.go
test/e2e/framework/identityvalidator/identityvalidator_helpers.go
test/e2e/init_containers_test.go
test/e2e/invalid_identities_test.go
test/e2e/multiple_identities_test.go
test/e2e/node_test.go
test/e2e/single_identity_test.go
test/image/identityvalidator/identityvalidator.go

- Enhances e2e tests to validate with `resourceID` along with `clientID`
fixes #679 

test: add e2e tests with resource id

---

.pipelines/soak-tests-template.yml
test/e2e/cluster_configs/vmas.json
test/e2e/cluster_configs/vmss.json
test/e2e/framework/azure/vm_manager.go
test/e2e/framework/azure/vmss_manager.go
test/e2e/identity_exception_test.go

fix: set max pods and assign empty map for system-assigned identity cleanup

---

test/e2e/framework/azure/vm_manager.go
test/e2e/framework/azure/vmss_manager.go

Fixes https://dev.azure.com/azure/aad-pod-identity/_build/results?buildId=12452&view=logs&jobId=d34132c9-c567-574e-81c3-10e22b0eb456&j=d34132c9-c567-574e-81c3-10e22b0eb456&t=4f1c18c1-9aa8-5644-f886-bb4554109216

fix: assign empty struct to user-assigned identities when enabling system-assigned identity

---

deploy/infra/deployment.yaml
deploy/infra/noazurejson/deployment.yaml

For non-rbac clusters, the certs volume is still required for MIC to create admin config. Adding it back to the deployment manifest.
fixes #711 

fix: add certs volume for non-rbac manifests

---

.pipelines/soak-tests-template.yml

 fix: use single quotes when performing string comparsion in ADO

---

.pipelines/deploy-aks-cluster.yml
.pipelines/deploy-aks-engine-cluster.yml
.pipelines/e2e-tests-template.yml
.pipelines/nightly.yml
.pipelines/pr.yml
test/e2e/cluster_configs/vmas.json
test/e2e/cluster_configs/vmss.json

- Created `AKS_CLUSTER_VERSION` and `AKS_ENGINE_CLUSTER_VERSION` pipeline variables so we could download the correct version of kubectl during e2e
- Removed `parameters.k8sReleases` from `e2e-tests-template.yml` since we are only testing 1.18 and there is no plan to expand to other K8s versions
fixes #718.

ci: download the correct version of kubectl in e2e according to cluster version

---

manifest_staging/charts/aad-pod-identity/templates/mic-deployment.yaml
manifest_staging/charts/aad-pod-identity/templates/mic-exception.yaml
manifest_staging/charts/aad-pod-identity/templates/mic-secret.yaml
manifest_staging/charts/aad-pod-identity/templates/mic-serviceaccount.yaml
manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
manifest_staging/charts/aad-pod-identity/templates/nmi-serviceaccount.yaml

- Adds `namespace: {{ .Release.Namespace }}` to helm charts as helm template doesn't automatically generate it.
fixes #737 

fix: add release namespace to chart manifests

---

.pipelines/build-images.yml
.pipelines/cleanup-images.yml
.pipelines/deploy-aks-cluster.yml
.pipelines/load-tests-template.yml
.pipelines/nightly.yml
.pipelines/publish-load-test-result.yml
manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
test/load/azureidentity-template.yml
test/load/azureidentitybinding-template.yml
test/load/config-deployment-template.yml
test/load/deployment-template.yml

- Adds load test pipelines to nightly job for `managed` and `standard` mode with AKS clusters
fixes https://github.com/Azure/aad-pod-identity/issues/714

test: add load test pipeline to nightly job

---

pkg/k8s/client.go

The original error from getPodList is not reported.
Fix #761 

Report original error from getPodListRetry

---

pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go
pkg/crd/crd.go
pkg/mic/mic.go
pkg/stats/stats.go
pkg/stats/stats_test.go

Ensure stats collector doesn't aggregate stats from multiple runs.
fixes #749

fix: ensure stats collector doesn't aggregate stats from multiple runs

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovider_test.go
pkg/cloudprovider/vm.go
pkg/cloudprovider/vmss.go

- Exclude `429` from retriable error codes to prevent SDK from making retries.
- Check the response in future/GET result to check if `Retry-After` header exists and cache the back off value in client.
fixes https://github.com/Azure/aad-pod-identity/issues/677

feat: throttling - honor retry after header

---

manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
manifest_staging/deploy/infra/deployment-rbac.yaml
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/managed-mode-deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment-rbac.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml
test/e2e/framework/iptables/iptables_helpers.go

Adds `dnsPolicy: ClusterFirstWithHostNet` for NMI daemonset as that's the recommended policy for pods running on host network
fixes https://github.com/Azure/aad-pod-identity/issues/775

chore: set dnspolicy to clusterfirstwithhostnet for NMI

---

manifest_staging/charts/aad-pod-identity/templates/mic-deployment.yaml
manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml

Currently, even though AAD Pod Identity support exposing metrics, it is not possible to create a `PodMonitor` object as the containers do not expose the metrics port.
This PR fixes this.
no

Expose metrics port

---

Dockerfile
Makefile

Fixes #771
Fixes the following vulnerabilities:
- https://lists.debian.org/debian-security-announce/2020/msg00101.html by bumping libgnutls30 from 3.6.7-4+deb10u3 to 3.6.7-4+deb10u5
- https://lists.debian.org/debian-security-announce/2020/msg00089.html by bumping apt version from 1.8.2 to 1.8.2.1. 

chore: bump debian-base to v2.1.3 and debian-iptables to v12.1.2

---

pkg/mic/mic.go
pkg/nmi/managed.go
pkg/nmi/server/server.go
pkg/nmi/standard.go

- Adds logs for when pods are ignored because of missing labels, misconfigured label or no matching AzureIdentityBinding found for the label.
fixes #732 

chore: add logs for ignored pods

---

test/e2e/backward_compat_test.go
test/e2e/cleanup.go
test/e2e/disruptive_test.go
test/e2e/framework/azureassignedidentity/azureassignedidentity_helpers.go
test/e2e/framework/azureidentity/azureidentity_helpers.go
test/e2e/framework/azureidentitybinding/azureidentitybinding_helpers.go
test/e2e/framework/azurepodidentityexception/azurepodidentityexception_helpers.go
test/e2e/framework/config.go
test/e2e/framework/helm/helm_helpers.go
test/e2e/framework/identityvalidator/identityvalidator_helpers.go
test/e2e/framework/interfaces.go
test/e2e/framework/iptables/iptables_helpers.go
test/e2e/framework/mic/mic_helpers.go
test/e2e/framework/namespace/namespace_helpers.go
test/e2e/framework/node/node_helpers.go
test/e2e/framework/pod/pod_helpers.go
test/e2e/framework/timeout.go
test/e2e/gatekeeper_test.go
test/e2e/identity_exception_test.go
test/e2e/init_containers_test.go
test/e2e/invalid_identities_test.go
test/e2e/liveness_probe_test.go
test/e2e/multiple_identities_test.go
test/e2e/node_test.go
test/e2e/single_identity_test.go

test: cleanup pods before removing ns and refactor "eventually" calls 

---

test/e2e/node_test.go

test: move identity unassignment to eventually block

---

.pipelines/build-images.yml
.pipelines/cleanup-images.yml
.pipelines/e2e-tests-template.yml
.pipelines/load-tests-template.yml
.pipelines/scan-images.yml
.pipelines/soak-tests-template.yml
.pipelines/unit-tests-template.yml
Dockerfile
Makefile
manifest_staging/charts/aad-pod-identity/templates/mic-deployment.yaml
manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
manifest_staging/deploy/infra/deployment-rbac.yaml
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/managed-mode-deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment-rbac.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml
test/e2e/framework/identityvalidator/identityvalidator_helpers.go
test/e2e/liveness_probe_test.go
test/image/identityvalidator/identityvalidator.go

- Continuously monitoring for any image vulnerabilities with [trivy](https://github.com/aquasecurity/trivy)
- enabled docker buildkit for faster image building process (5 minutes -> under 2 minutes for building mic, nmi, identityvalidator and demo images)
- added "User" field to aad-pod-identity images and run MIC & NMI as root when deploying.
Fixes #794.
FIxes #805.

ci: include image scanning as part of CI & use distroless/static:nonroot as the base images

---

.pipelines/deploy-aks-cluster.yml

- Removes setting for `AKS_CLUSTER_VERSION` as the versions can go stale over time. Use the latest default in AKS for testing.

ci: remove aks cluster version in e2e

---

.pipelines/load-tests-template.yml
test/e2e/framework/identityvalidator/identityvalidator_helpers.go

With the change in the base image to distroless, we introduced `identityvalidator --sleep` instead of using the Linux `sleep` command to allow the pods to enter a hibernated state. This PR ensures the test framework is backward compatible in case of using an older version identityvalidator in our soak test.

fix: ensure backward compability of identityvalidator image

---

.pipelines/e2e-tests-template.yml

The MC resource group is too long when the cluster location is in eastus2euap:
```
Operation failed with status: 'Bad Request'. Details: The length of the node resource group name is too long. The maximum length is 80 and the length of the value provided is 82. Please see https://aka.ms/aks-naming-rules for more details.
```

fix: decrease length of RG name to allow cluster creation in eastus2euap

---

manifest_staging/charts/aad-pod-identity/templates/mic-deployment.yaml

- Make `runAsUser: 0` conditional for MIC
- only run when access to `/etc/kubernetes/azure.json` is required.
fixes #836 

chore: make runAsUser conditional for MIC in helm

---

website/content/en/docs/Best Practices/_index.md

I've added an additional note to the bottom of the section `A pod using multiple AzureIdentities` found in [Best Practices](https://azure.github.io/aad-pod-identity/docs/best-practices/#a-pod-using-multiple-azureidentities). We found that although it is possible to allow a pod to utilise multiple identities, the documentation fails to mention you need to specify which identity should be use for a particular workload.  
**Issue Fixed**: N/A.
**Please answer the following questions with yes/no**: 
No.
N/A.

docs: add note about specifying which identity to use

---

hack/role-assignment.sh

fix: allow overwriting NODE_RESOURCE_GROUP in role-assignment.sh

---

website/content/en/docs/Configure/aad_pod_identity_on_kubenet.md

Since PodSecurityPolicy is on the way to deprecation, we should add instructions on how to mitigate the ARP spoofing vulnerability for kubenet clusters using OPA/Gatekeeper.
Fixes #893 
No
none

docs: Added instructions how to mitigate ARP spoofing on kubenet clusters with OPA/Gatekeeper

---

go.mod
test/e2e/README.md
test/e2e/framework/identityvalidator/identityvalidator_helpers.go
test/image/identityvalidator/identityvalidator.go
test/image/identityvalidator/keyvault.go
test/image/identityvalidator/sp.go

Made the following enhancements to identity validator:
- decrease context timeout from 150s to 80s to match the retry duration in NMI
- separated into `keyvaultTester` and `servicePrincipalTester` for modularity
- removed `--resource-group` flag since it is no used
- when generating an ADAL token with resource ID of a user-assigned identity, only parse response body from `http://169.254.169.254/metadata/identity/oauth2/token?resource=<resource>&msi_res_id=<msi_res_id>` when the status code is 200 and limited the request duration to 80 seconds
- check the secret obtained from the keyvault against the expected secret value
- clearer error messages
- add retry logic if we encounter "Identity not found" error (related to IMDS caching issue)
**Issue …

test: less error-prone identityvalidator 

---

Dockerfile

Temporary bandage for #904 until the debian-iptables image is patched.

dockerfile: fix CVE-2020-1971

---

manifest_staging/charts/aad-pod-identity/templates/NOTES.txt

```
NAME: pi
LAST DEPLOYED: Tue Dec 15 13:22:42 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
You have successfully installed AAD Pod Identity in your Kubernetes cluster!
To verify that AAD Pod Identity has started in standard mode, run:
kubectl --namespace=default get pods -l "app.kubernetes.io/component=mic"
kubectl --namespace=default get pods -l "app.kubernetes.io/component=nmi"
forceNameSpaced configuration has been DEPRECATED and will be removed in a future release. Please use forceNamespaced instead.
Now you can follow the demos to get familiar with AAD Pod Identity: https://azure.github.io/aad-pod-identity/docs/demo/
```
Does this change …

helm: add notes

---

cmd/demo/main.go

ref: #918
New demo output:
```log
I0107 23:54:23.215900       1 main.go:42] starting aad-pod-identity demo pod default/demo 10.244.0.73
I0107 23:56:03.223398       1 main.go:167] curl -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-08-01": {"compute":{"location":"westus2","name":"aks-nodepool1-55282659-0","offer":"aks","osType":"Linux","placementGroupId":"","platformFaultDomain":"0","platformUpdateDomain":"0","publisher":"microsoft-aks","resourceGroupName":"MC_chuwon-aks_chuwon_westus2","sku":"aks-ubuntu-1604-202004","subscriptionId":"2d31b5ab-0ddc-4991-bf8d-61b6ad196f5a","tags":"aksEngineVersion:aks-release-v0.47.0-1-aks;creationSource:aks-aks-nodepool1-55282659-0;orchestrator:Kubernetes:1 …
```

cleanup: refactor demo code

---

Dockerfile

ref: #923
Upgrading NMI's base image from debian-iptables v12.1.2 to buster-v1.4.0 should fix all known CVEs. Also, iptables version got bumped from v1.8.3 to v1.8.5. 

dockerfile: upgrade debian-iptables to buster-v1.4.0

---

Dockerfile

- Switches back to using `golang:1.15` instead of `golang-alpine:1.15` to avoid invoking package manager calls for build.

chore: switch to using golang builder

---

.pipelines/templates/e2e-test.yml
.pipelines/templates/role-assignment.yml
pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovider_test.go
pkg/mic/mic.go
pkg/mic/mic_test.go
test/e2e/Makefile
test/e2e/framework/azure/azure_client.go
test/e2e/framework/azureidentity/azureidentity_helpers.go
test/e2e/identity_exception_test.go
test/e2e/node_test.go

If the cluster identity is used with the application pod, then when all pods using the identity are deleted, the cluster identity will get cleaned up by MIC. This will cause subsequent cloud provider operations to fail because the cluster identity no longer exists. The user would need to manually go and fix it by assigning the identity back. Instead this PR adds the cluster identity to the immutable identity list. The cluster identity will never be deleted by MIC.
fixes #979 
**Notes for …

feat: add cluster identity to immutable list

---

manifest_staging/charts/aad-pod-identity/values.yaml

Add missing `weight` key in node affinity example

---

cmd/nmi/main.go

If `--allow-network-plugin-kubenet` is set to true, then we can bypass the check as it's been explicitly set to allow by the user. 
fixes https://github.com/Azure/aad-pod-identity/issues/997

fix: skip kubenet check if allowed is true

---

pkg/cloudprovider/cloudprovider.go
pkg/cloudprovider/cloudprovider_test.go
test/e2e/framework/exec/kubectl.go

- Skip identity PATCH call when there are no identities to assign/un-assign as part of MIC sync cycle. This prevents accidental deletes of existing identities when the GET response for VM/VMSS contains out of date data.

fix: skip PATCH call if no identities to assign or un-assign

---

.pipelines/templates/load-test.yml
test/e2e/framework/azure/vm_manager.go
test/e2e/framework/azure/vmss_manager.go

Fixes test failures in https://dev.azure.com/AzureContainerUpstream/AAD%20Pod%20Identity/_build/results?buildId=19324&view=results.

test: use kubectl to get vmss name

---

Dockerfile

Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
Fixes CVEs in libssl1.1 and libzstd1
```
$ docker run k8s.gcr.io/build-image/debian-iptables:buster-v1.6.0 iptables                                                                                                                        
iptables v1.8.5 (legacy): no command specified
```

dockerfile: upgrade debian-iptables to buster-v1.6.0

---

pkg/crd/crd.go

Fixes type upgrade:
```log
F0505 18:18:32.670266       1 mic.go:343] type upgrade failed with error: failed to upgrade type, error: failed to set object for resource azureassignedidentities, error: AzureAssignedIdentity.aadpodidentity.k8s.io "n0-default-azid0" is invalid: [spec.azureBindingRef.apiVersion: Required value: must not be empty, spec.azureBindingRef.kind: Required value: must not be empty, spec.azureIdentityRef.apiVersion: Required value: must not be empty, spec.azureIdentityRef.kind: Required value: must not be empty]
```
Does this change contain code from or inspired by another project? If so, did you notify the …

fix: inject TypeMeta during type upgrade

---

manifest_staging/charts/aad-pod-identity/templates/mic-deployment.yaml

Addresses bug found in issue https://github.com/Azure/aad-pod-identity/issues/1059
Fixes #1059 

Automatically checksum the mic-secret secret to roll mic deployment

---

.pipelines/templates/scan-images.yml
go.mod
go.sum
test/e2e/go.mod
test/e2e/go.sum

chore: bump golang.org/x/crypto to v0.0.0-20201216223049-8b5274cf687f

---

website/content/en/docs/Getting started/role-assignment.md

This should make it clearer that the last CLI option is simply selecting TSV output.  In some ecosystems, long argument names do not strictly require a double hyphen preceding them, and this makes it clear that this is not one of those cases.
Clarify documentation

Update documentation to use separator between output flag & argument

---

test/e2e/gatekeeper_test.go
validation/gatekeeper/azureidentityformat_template.yaml
website/content/en/docs/Configure/azure_identity_validation.md

Fix e2e test
Fixes: #1089
Looks like there was a change in gatekeeper deployment manifests that causes e2e tests to fail with the below message:
```
STEP: kubectl apply --kubeconfig=/agent/_work/1/s/_output/aad-pod-identity-e2e-70b6/kubeconfig/kubeconfig.westus2.json --namespace=gatekeeper-9wnsd -f /tmp/470855604
error: error validating "/tmp/470855604": error validating data: [ValidationError(ConstraintTemplate.spec.crd.spec.names): unknown field "listKind" in sh.gatekeeper.templates.v1beta1.ConstraintTemplate.spec.crd.spec.na …
```

fix: Remove incorrect fields from gatekeeper e2e test

---

.pipelines/nightly.yml
.pipelines/pr.yml
test/e2e/framework/identityvalidator/identityvalidator_helpers.go

`Upstream Pool` has been renamed to `staging-pool`.

ci: switch to `staging-pool`

---

config/crd/aadpodidentity.k8s.io.yaml
manifest_staging/charts/aad-pod-identity/crds/crd.yaml
manifest_staging/deploy/infra/deployment-rbac.yaml
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/managed-mode-deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment-rbac.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml
pkg/apis/aadpodidentity/v1/types.go

Adds additional columns to kubectl output for AAD Pod Identity Custom Resources.
- #829 
- #830 

Add additional columns to kubectl output

---

Dockerfile

Fixes the following CVEs:
```
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
|   LIBRARY   | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION  |                 TITLE                 |
+-------------+------------------+----------+-------------------+-----------------+---------------------------------------+
| libgcrypt20 | CVE-2021-33560   | HIGH     | 1.8.4-5           | 1.8.4-5+deb10u1 | libgcrypt: mishandles ElGamal         |
|             |                  |          |                   |                 | encryption because it lacks           |
|             |                  |          |                   | …
```

dockerfile: upgrade multiple packages due to CVEs

---

Dockerfile

chore: update debian base to buster-v1.6.5

---

.pipelines/templates/e2e-test.yml
pkg/apis/aadpodidentity/sort.go
pkg/apis/aadpodidentity/sort_test.go
pkg/mic/mic.go
test/e2e/framework/azureassignedidentity/azureassignedidentity_helpers.go
test/e2e/name_conflict_test.go

Fixes #1065 
Deployed two AzureIdentity and AzureIdentityBinding in the default and test namespace with the same name and selector. Unable to repro the issue with this PR:
```
I0623 17:08:49.859982       1 main.go:114] starting mic process. Version: v0.0.0-dev. Build date: 2021-06-23-17:07
W0623 17:08:49.860054       1 main.go:119] --kubeconfig not passed will use InClusterConfig
I0623 17:08:49.860063       1 main.go:136] kubeconfig () cloudconfig (/etc/kubernetes/azure.json)
I0623 17:08:49.860240       1 main.go:144] running MIC in namespaced mode: false
I0623 17:08:49.860250       1 main.go:148] client QPS set to: 5. Burst to: 5
I0623 17:08:49.860269       1 mic.go:138] starting to create the pod identity client. …
```

fix: prevent overwriting of AzureAssignedIdentity when creating it

---

Dockerfile
manifest_staging/deploy/infra/deployment.yaml
manifest_staging/deploy/infra/noazurejson/deployment.yaml

AKS is rolling out the TLS bootstrapping change. Before this change, AKS cluster agent node uses kubeconfig as follow:
```yaml
apiVersion: v1
kind: Config
clusters:
- name: localcluster
cluster:
certificate-authority: /etc/kubernetes/certs/ca.crt
server: https://<api-server-address>:443
users:
- name: client
user:
client-certificate: /etc/kubernetes/certs/client.crt
client-key: /etc/kubernetes/certs/client.key
contexts:
- context:
cluster: localcluster
user: client
name: localclustercontext
current-context: localclustercontext
```
After enabling TLS bootstrapping, the agent node will get the kubeconfig as follow:
```yaml
apiVersion: v1
clusters:
- cluster:
certificate-authority: /etc/kubernetes/certs/ca.crt
server: https://<api-server-address>:443
name: …
```

fix: mount kubelet config to `/var/lib/kubelet` for non-rbac deployment

---

test/e2e/framework/config.go
test/e2e/framework/helm/helm_helpers.go
test/e2e/retry_after_header_test.go

Fixes test failures in https://dev.azure.com/AzureContainerUpstream/AAD%20Pod%20Identity/_build/results?buildId=24228&view=results. We have to reuse helm values during helm upgrade so existing values won't be overwritten by the default values.

test: reuse helm values during helm upgrade

---

.github/ISSUE_TEMPLATE/bug_report.md

The troubleshooting and known issues links in the bug report template have been broken since the docs moved to azure.github.io.

Fix broken URLs in issue template

---

Dockerfile

- Bumps the `debian-iptables` base image to `buster-v1.6.6`

chore: update debian-iptables base to buster-v1.6.6

---

.pipelines/templates/cleanup-role-assignments.yml
.pipelines/templates/e2e-test.yml
.pipelines/templates/role-assignment.yml
pkg/nmi/standard.go

- Fixes #1136 
- cleanup role assignments for ACR and keyvault

chore: add redacted client ID in the error log & cleanup role assignments

---

Dockerfile
test/e2e/framework/iptables/iptables_helpers.go

Signed-off-by: GitHub <noreply@github.com>
Update debian-iptables to buster-v1.6.7.

chore: update debian-iptables to buster-v1.6.7

---

pkg/mic/mic.go
pkg/mic/mic_test.go

In case of stateful sets, the pod with the same name could move from one node to another still bound to the same `AzureIdentity`. Currently in such scenarios, the `nodename` label in metadata for `AzureAssignedIdentity` isn't updated to reflect the node change. This will cause token request to fail as NMI has filtered watch based on nodename.
We need to use the old object metadata because resourceVersion needs to be set as part of update. This PR uses the existing object metadata and updates just the labels to latest. 
Does this change contain code from or inspired by another project? If so, did you notify the …

fix: update the node name label as part of `AzureAssignedIdentity` update

---

website/content/en/docs/_index.md

Fix typo "clutster" --> "cluster" on homepage of the docs

Fix type in homepage docs

---

cmd/demo/main.go
pkg/auth/auth.go
pkg/auth/errors.go
pkg/auth/errors_test.go
pkg/cloudprovider/cloudprovider.go
pkg/nmi/server/server.go
test/image/identityvalidator/identityvalidator.go
test/image/identityvalidator/keyvault.go
test/image/identityvalidator/sp.go

- Parse the error from adal token request to distinguish token request error from IMDS health check failures.
- If IMDS health check fails, return a 503
- For token request failures, keep the same behavior and return 403
- Update the token request method in all the packages as the current ones we're using are deprecated.

feat: return http 503 when IMDS healthcheck fails 

---

test/e2e/framework/helm/helm_helpers.go

Helm upgrade commands in soak cluster are failing because of the new `mic.customCloud.enabled` value in helm chart. As this doesn't exist in the old chart, it fails with nil pointer exception with `--reuse-values`.

test: fix helm upgrade for soak test

---

Dockerfile

Fixes CVE-2021-43618 - https://dev.azure.com/AzureContainerUpstream/AAD%20Pod%20Identity/_build/results?buildId=34429&view=logs&j=7e664a44-1d98-5348-601c-dff379a14ab5&t=df0bac15-41b8-536a-5d4e-7c9def102aed

security: fix CVE-2021-43618

---

README.md
website/content/en/docs/_index.md

Adding a disclaimer in README.md and website/content/en/docs/_index.md for the current project status.

docs: add disclaimer for current project status

---

manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
website/content/en/changelog/_index.md
website/content/en/docs/_index.md

fix: make metadata header required configurable in helm

---

Dockerfile

```bash
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| LIBRARY  | VULNERABILITY ID | SEVERITY | INSTALLED VERSION |  FIXED VERSION   |                TITLE                 |
+----------+------------------+----------+-------------------+------------------+--------------------------------------+
| bsdutils | CVE-2021-3995    | MEDIUM   | 2.36.1-8          | 2.36.1-8+deb11u1 | util-linux: Unauthorized unmount     |
|          |                  |          |                   |                  | of FUSE filesystems belonging        |
|          |                  |          |                   |                  | to users with similar …
```

security: fix CVE-2021-3995, CVE-2021-3996

---

cmd/nmi/main.go
go.mod
go.sum
manifest_staging/charts/aad-pod-identity/templates/nmi-daemonset.yaml
manifest_staging/charts/aad-pod-identity/values.yaml
pkg/nmi/conntrack/conntrack.go
pkg/nmi/server/server.go
website/content/en/docs/Configure/feature_flags.md

We have observed that in certain conditions iptables nat rules that are added by nmi pod don`t have any efect on preexisting connections.  This causes traffic to flow directly to metadata endpoint instead of being intercepted by nmi pod.
Have added a utility function to delete conntrack entries which point to metadata endpoint( ip and port comination)

fix: delete conntrack entries after adding iptables rules on initialization

---

manifest_staging/charts/aad-pod-identity/templates/mic-pod-disruption-budget.yaml

```bash
W0308 11:33:22.266486   44226 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0308 11:33:22.317510   44226 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```
fixes https://github.com/Azure/aad-pod-identity/issues/1253

chore: use policy/v1 for PodDisruptionBudget

---

charts/aad-pod-identity/values.yaml
manifest_staging/charts/aad-pod-identity/values.yaml

A colon was missing in the `nodeAffinity` sample comment ... for less experienced k8s user this is not an error easy to catch 😄
Just modifying comments, no biggie 😄

fix: update nmi affinity sample in helm charts

---

Dockerfile

Fixes Critical CVE-2022-23218 in libc and libc-bin

security: fix critical CVE-2022-23218

---

Dockerfile

chore: upgrade to debian-iptables:bullseye-v1.3.0

---

Dockerfile

- Update debian-iptables to bullseye-v1.4.0
- Fix CVE-2022-1664

security: fix CVE-2022-1664

---

cmd/nmi/main.go
pkg/nmi/server/server.go

When using NMI on a cluster using cilium as CNI, the iptables DNAT rule that intercepts traffic towards IMDS has to be replaced by a CiliumLocalRedirectPolicy that works using eBPF.
In practice, it means that traffic is redirected to `add-pod-identity` pod's IP (which is the node IP) rather than 127.0.0.1.
This currently fails, because NMI only listens to localhost.
See https://github.com/cilium/cilium/issues/20103 for more details
This PR adds a new flag to allow specifying which address port 2579 should listen to.
The …

Allow selecting bind address for NMI

---

Dockerfile

- update debian-iptables to bullseye-v1.5.0

chore: update debian-iptables to bullseye-v1.5.0

---

pkg/nmi/server/server.go

If the Content-Length header is not explicitly set and the length is > 2048 bytes, writer.Write() method will automatically set the `Transfer-Encoding: Chunked`. To avoid this, we are setting the content length to the len of response when returning from NMI.

fix: set Content-Length header in NMI response

---

Dockerfile

- update debian-iptables to bullseye-v1.5.1

chore: update debian-iptables to bullseye-v1.5.1

---

pkg/nmi/server/server.go
pkg/nmi/server/server_test.go

fix: add handler for invalid token requests

---

README.md
website/content/en/changelog/_index.md
website/content/en/docs/_index.md

- Adds an anchor for announcement, so it can be shared with the `#announcement` anchor. 

docs: add an anchor for deprecation announcement

---

pkg/nmi/server/server.go
pkg/nmi/server/server_test.go

In the latest .Net ["Azure.Identity" SDK](https://www.nuget.org/packages/Azure.Identity) (v1.8.2), the get identity token request to IMDS with resource id is like this:
Caller method example:
`var token = new ManagedIdentityCredential("<resourceId>").GetToken(<token request context>)`
HTTP request: _/metadata/identity/oauth2/token?api-version=...&resource=...&**mi_res_id**=<resource_id>_
So nmi needs to read both "mi_res_id" and "msi_res_id"(backward compatible) values.
Does this change contain code from or inspired by another project?  -  no
from Microsoft COSMIC team.

Update NMI server resource id query key

---

Dockerfile

- update debian-iptables to bullseye-v1.5.4

chore: update debian-iptables to bullseye-v1.5.4

---

.github/workflows/codecov.yml
.github/workflows/gh-pages.yml

- The `gh-pages` [publish workflow](https://github.com/Azure/aad-pod-identity/actions/runs/4997336268/jobs/8970870915) has been waiting for runner since yesterday and this could be because `ubuntu-18.04` is not supported anymore. Updating the workflows to use `ubuntu-latest` runner.

chore: use ubuntu-latest gh runner

---

.github/workflows/codecov.yml
.github/workflows/gh-pages.yml

- explicitly set permissions for each workflow
- changed the default workflow permissions to read only with this change.

ci: restrict permissions for gh workflows
